<?php
$supported_languages = [
    'af'=> __('Afrikaans','auto-translate'),
    'sq' => __('Albanian','auto-translate'),
    'am' => __('Amharic','auto-translate'),
    'ar' => __('Arabic','auto-translate'),
    'hy' => __('Armenian','auto-translate'),
    'az' => __('Azerbaijani','auto-translate'),
    'eu' => __('Basque','auto-translate'),
    'be' => __('Belarusian','auto-translate'),
    'bn' => __('Bengali','auto-translate'),
    'bs' => __('Bosnian','auto-translate'),
    'bg' => __('Bulgarian','auto-translate'),
    'ca' => __('Catalan','auto-translate'),
    'ceb' => __('Cebuano','auto-translate'),
    'ny' => __('Chichewa','auto-translate'),
    'zh-CN' => __('Chinese (Simplified)','auto-translate'),
    'zh-TW' => __('Chinese (Traditional)','auto-translate'),
    'co' => __('Corsican','auto-translate'),
    'hr' => __('Croatian','auto-translate'),
    'cs' => __('Czech','auto-translate'),
    'da' => __('Danish','auto-translate'),
    'nl' => __('Dutch ','auto-translate'),
    'en' => __('English','auto-translate'),
    'eo' => __('Esperanto','auto-translate'),
    'et' => __('Estonian','auto-translate'),
    'tl' => __('Filipino','auto-translate'),
    'fi' => __('Finnish','auto-translate'),
    'fr' => __('French','auto-translate'),
    'fy' => __('Frisian','auto-translate'),
    'gl' => __('Galician','auto-translate'),
    'ka' => __('Georgian','auto-translate'),
    'de' => __('German','auto-translate'),
    'el' => __('Greek','auto-translate'),
    'gu' => __('Gujarati','auto-translate'),
    'ht' => __('Haitian Creole','auto-translate'),
    'ha' => __('Hausa','auto-translate'),
    'haw' => __('Hawaiian','auto-translate'),
    'iw' => __('Hebrew','auto-translate'),
    'hi' => __('Hindi','auto-translate'),
    'hmn' => __('Hmong','auto-translate'),
    'hu' => __('Hungarian','auto-translate'),
    'is' => __('Icelandic','auto-translate'),
    'ig' => __('Igbo','auto-translate'),
    'id' => __('Indonesian','auto-translate'),
    'ga' => __('Irish','auto-translate'),
    'it' => __('Italian','auto-translate'),
    'ja' => __('Japanese','auto-translate'),
    'jw' => __('Javanese','auto-translate'),
    'kn' => __('Kannada','auto-translate'),
    'kk' => __('Kazakh','auto-translate'),
    'km' => __('Khmer','auto-translate'),
    'ko' => __('Korean','auto-translate'),
    'ku' => __('Kurdish (Kurmanji)','auto-translate'),
    'ky' => __('Kyrgyz','auto-translate'),
    'lo' => __('Lao','auto-translate'),
    'la' => __('Latin','auto-translate'),
    'lv' => __('Latvian','auto-translate'),
    'lt' => __('Lithuanian','auto-translate'),
    'lb' => __('Luxembourgish','auto-translate'),
    'mk' => __('Macedonian','auto-translate'),
    'mg' => __('Malagasy','auto-translate'),
    'ms' => __('Malay','auto-translate'),
    'ml' => __('Malayalam','auto-translate'),
    'mt' => __('Maltese','auto-translate'),
    'mi' => __('Maori','auto-translate'),
    'mr' => __('Marathi','auto-translate'),
    'mn' => __('Mongolian','auto-translate'),
    'my' => __('Myanmar (Burmese)','auto-translate'),
    'ne' => __('Nepali','auto-translate'),
    'no' => __('Norwegian','auto-translate'),
    'ps' => __('Pashto','auto-translate'),
    'fa' => __('Persian','auto-translate'),
    'pl' => __('Polish','auto-translate'),
    'pt' => __('Portuguese','auto-translate'),
    'pa' => __('Punjabi','auto-translate'),
    'ro' => __('Romanian','auto-translate'),
    'ru' => __('Russian','auto-translate'),
    'sm' => __('Samoan','auto-translate'),
    'gd' => __('Scots Gaelic','auto-translate'),
    'sr' => __('Serbian','auto-translate'),
    'st' => __('Sesotho','auto-translate'),
    'sn' => __('Shona','auto-translate'),
    'sd' => __('Sindhi','auto-translate'),
    'si' => __('Sinhala','auto-translate'),
    'sk' => __('Slovak','auto-translate'),
    'sl' => __('Slovenian','auto-translate'),
    'so' => __('Somali','auto-translate'),
    'es' => __('Spanish','auto-translate'),
    'su' => __('Sundanese','auto-translate'),
    'sw' => __('Swahili','auto-translate'),
    'sv' => __('Swedish','auto-translate'),
    'tg' => __('Tajik','auto-translate'),
    'ta' => __('Tamil','auto-translate'),
    'te' => __('Telugu','auto-translate'),
    'th' => __('Thai','auto-translate'),
    'tr' => __('Turkish','auto-translate'),
    'uk' => __('Ukrainian','auto-translate'),
    'ur' => __('Urdu','auto-translate'),
    'uz' => __('Uzbek','auto-translate'),
    'vi' => __('Vietnamese','auto-translate'),
    'cy' => __('Welsh','auto-translate'),
    'xh' => __('Xhosa','auto-translate'),
    'yi' => __('Yiddish','auto-translate'),
    'yo' => __('Yoruba','auto-translate'),
    'zu' => __('Zulu','auto-translate')
];

$widget_types = [
    'classic' => __('Classic','auto-translate'),
    'minimalist' => __('Minimalist','auto-translate'),
];

$languages_countries = [
    'af' => ['lang_name' => __('Afrikaans', 'auto-translate'), 'lang_code' => 'af', 'countries' => [['country_code' => 'za', 'country_name' => __('South Africa', 'auto-translate')],['country_code' => 'bw', 'country_name' => __('Botswana', 'auto-translate')],['country_code' => 'na', 'country_name' => __('Namibia', 'auto-translate')],]],
    'sq' => ['lang_name' => __('Albanian', 'auto-translate'), 'lang_code' => 'sq', 'countries' => [['country_code' => 'al', 'country_name' => __('Albania', 'auto-translate')],['country_code' => 'xk', 'country_name' => __('Kosovo', 'auto-translate')],['country_code' => 'mk', 'country_name' => __('North Macedonia', 'auto-translate')],]],
    'am' => ['lang_name' => __('Amharic', 'auto-translate'), 'lang_code' => 'am', 'countries' => [['country_code' => 'et', 'country_name' => __('Ethiopia', 'auto-translate')],]],
    'ar' => ['lang_name' => __('Arabic', 'auto-translate'), 'lang_code' => 'ar', 'countries' => [['country_code' => 'sa', 'country_name' => __('Saudi Arabia', 'auto-translate')],['country_code' => 'dz', 'country_name' => __('Algeria', 'auto-translate')],['country_code' => 'bh', 'country_name' => __('Bahrain', 'auto-translate')],['country_code' => 'td', 'country_name' => __('Chad', 'auto-translate')],['country_code' => 'km', 'country_name' => __('Comoros', 'auto-translate')],['country_code' => 'dj', 'country_name' => __('Djibouti', 'auto-translate')],['country_code' => 'eg', 'country_name' => __('Egypt', 'auto-translate')],['country_code' => 'iq', 'country_name' => __('Iraq', 'auto-translate')],['country_code' => 'jo', 'country_name' => __('Jordan', 'auto-translate')],['country_code' => 'kw', 'country_name' => __('Kuwait', 'auto-translate')],['country_code' => 'lb', 'country_name' => __('Lebanon', 'auto-translate')],['country_code' => 'ly', 'country_name' => __('Libya', 'auto-translate')],['country_code' => 'mr', 'country_name' => __('Mauritania', 'auto-translate')],['country_code' => 'ma', 'country_name' => __('Morocco', 'auto-translate')],['country_code' => 'om', 'country_name' => __('Oman', 'auto-translate')],['country_code' => 'ps', 'country_name' => __('Palestine', 'auto-translate')],['country_code' => 'qa', 'country_name' => __('Qatar', 'auto-translate')],['country_code' => 'so', 'country_name' => __('Somalia', 'auto-translate')],['country_code' => 'sd', 'country_name' => __('Sudan', 'auto-translate')],['country_code' => 'sy', 'country_name' => __('Syria', 'auto-translate')],['country_code' => 'tn', 'country_name' => __('Tunisia', 'auto-translate')],['country_code' => 'ae', 'country_name' => __('United Arab Emirates', 'auto-translate')],['country_code' => 'ye', 'country_name' => __('Yemen', 'auto-translate')],]],
    'hy' => ['lang_name' => __('Armenian', 'auto-translate'), 'lang_code' => 'hy', 'countries' => [['country_code' => 'am', 'country_name' => __('Armenia', 'auto-translate')],]],
    'az' => ['lang_name' => __('Azerbaijani', 'auto-translate'), 'lang_code' => 'az', 'countries' => [['country_code' => 'az', 'country_name' => __('Azerbaijan', 'auto-translate')],]],
    'eu' => ['lang_name' => __('Basque', 'auto-translate'), 'lang_code' => 'eu', 'countries' => [['country_code' => 'es-pv', 'country_name' => __('Basque Country', 'auto-translate')],]],
    'be' => ['lang_name' => __('Belarusian', 'auto-translate'), 'lang_code' => 'be', 'countries' => [['country_code' => 'by', 'country_name' => __('Belarus', 'auto-translate')],]],
    'bn' => ['lang_name' => __('Bengali', 'auto-translate'), 'lang_code' => 'bn', 'countries' => [['country_code' => 'bd', 'country_name' => __('Bangladesh', 'auto-translate')],]],
    'bs' => ['lang_name' => __('Bosnian', 'auto-translate'), 'lang_code' => 'bs', 'countries' => [['country_code' => 'ba', 'country_name' => __('Bosnia and Herzegovina', 'auto-translate')],]],
    'bg' => ['lang_name' => __('Bulgarian', 'auto-translate'), 'lang_code' => 'bg', 'countries' => [['country_code' => 'bg', 'country_name' => __('Bulgaria', 'auto-translate')],]],
    'ca' => ['lang_name' => __('Catalan', 'auto-translate'), 'lang_code' => 'ca', 'countries' => [['country_code' => 'es-ct', 'country_name' => __('Catalonia', 'auto-translate')],['country_code' => 'ad', 'country_name' => __('Andorra', 'auto-translate')],]],
    'ceb' => ['lang_name' => __('Cebuano', 'auto-translate'), 'lang_code' => 'ceb', 'countries' => [['country_code' => 'ph', 'country_name' => __('Philippines', 'auto-translate')],]],
    'ny' => ['lang_name' => __('Chichewa', 'auto-translate'), 'lang_code' => 'ny', 'countries' => [['country_code' => 'mz', 'country_name' => __('Malawi', 'auto-translate')],['country_code' => 'zw', 'country_name' => __('Zimbabwe', 'auto-translate')],]],
    'zh-CN' => ['lang_name' => __('Chinese (Simplified)', 'auto-translate'), 'lang_code' => 'zh-CN', 'countries' => [['country_code' => 'cn', 'country_name' => __('China', 'auto-translate')],['country_code' => 'my', 'country_name' => __('Malaysia', 'auto-translate')],['country_code' => 'sg', 'country_name' => __('Singapore', 'auto-translate')],]],
    'zh-TW' => ['lang_name' => __('Chinese (Traditional)', 'auto-translate'), 'lang_code' => 'zh-TW', 'countries' => [['country_code' => 'tw', 'country_name' => __('Taiwan', 'auto-translate')],['country_code' => 'hk', 'country_name' => __('Hong Kong', 'auto-translate')],['country_code' => 'mo', 'country_name' => __('Macau', 'auto-translate')],]],
    'co' => ['lang_name' => __('Corsican', 'auto-translate'), 'lang_code' => 'co', 'countries' => [['country_code' => 'fr-h', 'country_name' => __('Corsica', 'auto-translate')],]],
    'hr' => ['lang_name' => __('Croatian', 'auto-translate'), 'lang_code' => 'hr', 'countries' => [['country_code' => 'hr', 'country_name' => __('Croatia', 'auto-translate')],['country_code' => 'ba', 'country_name' => __('Bosnia and Herzegovina', 'auto-translate')],]],
    'cs' => ['lang_name' => __('Czech', 'auto-translate'), 'lang_code' => 'cs', 'countries' => [['country_code' => 'cz', 'country_name' => __('Czech Republic', 'auto-translate')],]],
    'da' => ['lang_name' => __('Danish', 'auto-translate'), 'lang_code' => 'da', 'countries' => [['country_code' => 'dk', 'country_name' => __('Denmark', 'auto-translate')],]],
    'nl' => ['lang_name' => __('Dutch', 'auto-translate'), 'lang_code' => 'nl', 'countries' => [['country_code' => 'nl', 'country_name' => __('Netherlands', 'auto-translate')],['country_code' => 'be', 'country_name' => __('Belgium', 'auto-translate')],['country_code' => 'sr', 'country_name' => __('Suriname', 'auto-translate')],]],
    'en' => ['lang_name' => __('English', 'auto-translate'), 'lang_code' => 'en', 'countries' => [['country_code' => 'gb', 'country_name' => __('United Kingdom', 'auto-translate')],['country_code' => 'us', 'country_name' => __('United States', 'auto-translate')],['country_code' => 'au', 'country_name' => __('Australia', 'auto-translate')],['country_code' => 'ca', 'country_name' => __('Canada', 'auto-translate')],['country_code' => 'ie', 'country_name' => __('Ireland', 'auto-translate')],['country_code' => 'nz', 'country_name' => __('New Zealand', 'auto-translate')],['country_code' => 'ng', 'country_name' => __('Nigeria', 'auto-translate')],['country_code' => 'za', 'country_name' => __('South Africa', 'auto-translate')],['country_code' => 'ke', 'country_name' => __('Kenya', 'auto-translate')],['country_code' => 'gh', 'country_name' => __('Ghana', 'auto-translate')],['country_code' => 'ss', 'country_name' => __('South Sudan', 'auto-translate')],['country_code' => 'sl', 'country_name' => __('Sierra Leone', 'auto-translate')],['country_code' => 'sg', 'country_name' => __('Singapore', 'auto-translate')],['country_code' => 'lr', 'country_name' => __('Liberia', 'auto-translate')],['country_code' => 'jm', 'country_name' => __('Jamaica', 'auto-translate')],]],
    'eo' => ['lang_name' => __('Esperanto', 'auto-translate'), 'lang_code' => 'eo', 'countries' => [['country_code' => 'eo', 'country_name' => __('Esperanto', 'auto-translate')],]],
    'et' => ['lang_name' => __('Estonian', 'auto-translate'), 'lang_code' => 'et', 'countries' => [['country_code' => 'ee', 'country_name' => __('Estonia', 'auto-translate')],]],
    'tl' => ['lang_name' => __('Filipino', 'auto-translate'), 'lang_code' => 'tl', 'countries' => [['country_code' => 'ph', 'country_name' => __('Philippines', 'auto-translate')],]],
    'fi' => ['lang_name' => __('Finnish', 'auto-translate'), 'lang_code' => 'fi', 'countries' => [['country_code' => 'fi', 'country_name' => __('Finland', 'auto-translate')],]],
    'fr' => ['lang_name' => __('French', 'auto-translate'), 'lang_code' => 'fr', 'countries' => [['country_code' => 'fr', 'country_name' => __('France', 'auto-translate')],['country_code' => 'ca-pq', 'country_name' => __('Quebec', 'auto-translate')],['country_code' => 'be', 'country_name' => __('Belgium', 'auto-translate')],['country_code' => 'ch', 'country_name' => __('Switzerland', 'auto-translate')],['country_code' => 'cd', 'country_name' => __('DR Congo', 'auto-translate')],['country_code' => 'cg', 'country_name' => __('Congo', 'auto-translate')],['country_code' => 'cm', 'country_name' => __('Cameroon', 'auto-translate')],['country_code' => 'ci', 'country_name' => __('Ivory Coast', 'auto-translate')],]],
    'fy' => ['lang_name' => __('Frisian', 'auto-translate'), 'lang_code' => 'fy', 'countries' => [['country_code' => 'nl-fr', 'country_name' => __('Friesland', 'auto-translate')],]],
    'gl' => ['lang_name' => __('Galician', 'auto-translate'), 'lang_code' => 'gl', 'countries' => [['country_code' => 'es-ga', 'country_name' => __('Galicia', 'auto-translate')],]],
    'ka' => ['lang_name' => __('Georgian', 'auto-translate'), 'lang_code' => 'ka', 'countries' => [['country_code' => 'ge', 'country_name' => __('Georgia', 'auto-translate')],]],
    'de' => ['lang_name' => __('German', 'auto-translate'), 'lang_code' => 'de', 'countries' => [['country_code' => 'de', 'country_name' => __('Germany', 'auto-translate')],['country_code' => 'at', 'country_name' => __('Austria', 'auto-translate')],['country_code' => 'ch', 'country_name' => __('Switzerland', 'auto-translate')],['country_code' => 'li', 'country_name' => __('Liechtenstein', 'auto-translate')],]],
    'el' => ['lang_name' => __('Greek', 'auto-translate'), 'lang_code' => 'el', 'countries' => [['country_code' => 'gr', 'country_name' => __('Greece', 'auto-translate')],['country_code' => 'cy', 'country_name' => __('Cyprus', 'auto-translate')],]],
    'gu' => ['lang_name' => __('Gujarati', 'auto-translate'), 'lang_code' => 'gu', 'countries' => [['country_code' => 'in-gj', 'country_name' => __('Gujarat', 'auto-translate')],]],
    'ht' => ['lang_name' => __('Haitian Creole', 'auto-translate'), 'lang_code' => 'ht', 'countries' => [['country_code' => 'ht', 'country_name' => __('Haiti', 'auto-translate')],]],
    'ha' => ['lang_name' => __('Hausa', 'auto-translate'), 'lang_code' => 'ha', 'countries' => [['country_code' => 'ng', 'country_name' => __('Nigeria', 'auto-translate')],['country_code' => 'ne', 'country_name' => __('Niger', 'auto-translate')],]],
    'haw' => ['lang_name' => __('Hawaiian', 'auto-translate'), 'lang_code' => 'haw', 'countries' => [['country_code' => 'us-hi', 'country_name' => __('Hawaii', 'auto-translate')],]],
    'iw' => ['lang_name' => __('Hebrew', 'auto-translate'), 'lang_code' => 'iw', 'countries' => [['country_code' => 'il', 'country_name' => __('Israel', 'auto-translate')],]],
    'hi' => ['lang_name' => __('Hindi', 'auto-translate'), 'lang_code' => 'hi', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],['country_code' => 'pk', 'country_name' => __('Pakistan', 'auto-translate')],]],
    'hmn' => ['lang_name' => __('Hmong', 'auto-translate'), 'lang_code' => 'hmn', 'countries' => [['country_code' => 'cn', 'country_name' => __('China', 'auto-translate')],['country_code' => 'vn', 'country_name' => __('Vietnam', 'auto-translate')],['country_code' => 'la', 'country_name' => __('Laos', 'auto-translate')],['country_code' => 'mm', 'country_name' => __('Myanmar', 'auto-translate')],['country_code' => 'th', 'country_name' => __('Thailand', 'auto-translate')],]],
    'hu' => ['lang_name' => __('Hungarian', 'auto-translate'), 'lang_code' => 'hu', 'countries' => [['country_code' => 'hu', 'country_name' => __('Hungary', 'auto-translate')],]],
    'is' => ['lang_name' => __('Icelandic', 'auto-translate'), 'lang_code' => 'is', 'countries' => [['country_code' => 'is', 'country_name' => __('Iceland', 'auto-translate')],]],
    'ig' => ['lang_name' => __('Igbo', 'auto-translate'), 'lang_code' => 'ig', 'countries' => [['country_code' => 'ng', 'country_name' => __('Nigeria', 'auto-translate')],]],
    'id' => ['lang_name' => __('Indonesian', 'auto-translate'), 'lang_code' => 'id', 'countries' => [['country_code' => 'id', 'country_name' => __('Indonesia', 'auto-translate')],]],
    'ga' => ['lang_name' => __('Irish', 'auto-translate'), 'lang_code' => 'ga', 'countries' => [['country_code' => 'ie', 'country_name' => __('Ireland', 'auto-translate')],]],
    'it' => ['lang_name' => __('Italian', 'auto-translate'), 'lang_code' => 'it', 'countries' => [['country_code' => 'it', 'country_name' => __('Italy', 'auto-translate')],]],
    'ja' => ['lang_name' => __('Japanese', 'auto-translate'), 'lang_code' => 'ja', 'countries' => [['country_code' => 'jp', 'country_name' => __('Japan', 'auto-translate')],]],
    'jw' => ['lang_name' => __('Javanese', 'auto-translate'), 'lang_code' => 'jw', 'countries' => [['country_code' => 'id', 'country_name' => __('Indonesia', 'auto-translate')],]],
    'kn' => ['lang_name' => __('Kannada', 'auto-translate'), 'lang_code' => 'kn', 'countries' => [['country_code' => 'in-ka', 'country_name' => __('Karnataka', 'auto-translate')],]],
    'kk' => ['lang_name' => __('Kazakh', 'auto-translate'), 'lang_code' => 'kk', 'countries' => [['country_code' => 'kz', 'country_name' => __('Kazakhstan', 'auto-translate')],]],
    'km' => ['lang_name' => __('Khmer', 'auto-translate'), 'lang_code' => 'km', 'countries' => [['country_code' => 'kh', 'country_name' => __('Cambodia', 'auto-translate')],]],
    'ko' => ['lang_name' => __('Korean', 'auto-translate'), 'lang_code' => 'ko', 'countries' => [['country_code' => 'kr', 'country_name' => __('South Korea', 'auto-translate')],['country_code' => 'kp', 'country_name' => __('North Korea', 'auto-translate')],]],
    'ku' => ['lang_name' => __('Kurdish (Kurmanji)', 'auto-translate'), 'lang_code' => 'ku', 'countries' => [['country_code' => 'iq-kr', 'country_name' => __('Kurdistan', 'auto-translate')],]],
    'ky' => ['lang_name' => __('Kyrgyz', 'auto-translate'), 'lang_code' => 'ky', 'countries' => [['country_code' => 'kg', 'country_name' => __('Kyrgyzstan', 'auto-translate')],]],
    'lo' => ['lang_name' => __('Lao', 'auto-translate'), 'lang_code' => 'lo', 'countries' => [['country_code' => 'la', 'country_name' => __('Laos', 'auto-translate')],]],
    'la' => ['lang_name' => __('Latin', 'auto-translate'), 'lang_code' => 'la', 'countries' => [['country_code' => 'rom', 'country_name' => __('Rome', 'auto-translate')],]],
    'lv' => ['lang_name' => __('Latvian', 'auto-translate'), 'lang_code' => 'lv', 'countries' => [['country_code' => 'lv', 'country_name' => __('Latvia', 'auto-translate')],]],
    'lt' => ['lang_name' => __('Lithuanian', 'auto-translate'), 'lang_code' => 'lt', 'countries' => [['country_code' => 'lt', 'country_name' => __('Lithuania', 'auto-translate')],]],
    'lb' => ['lang_name' => __('Luxembourgish', 'auto-translate'), 'lang_code' => 'lb', 'countries' => [['country_code' => 'lu', 'country_name' => __('Luxembourg', 'auto-translate')],]],
    'mk' => ['lang_name' => __('Macedonian', 'auto-translate'), 'lang_code' => 'mk', 'countries' => [['country_code' => 'mk', 'country_name' => __('North Macedonia', 'auto-translate')],]],
    'mg' => ['lang_name' => __('Malagasy', 'auto-translate'), 'lang_code' => 'mg', 'countries' => [['country_code' => 'mg', 'country_name' => __('Madagascar', 'auto-translate')],]],
    'ms' => ['lang_name' => __('Malay', 'auto-translate'), 'lang_code' => 'ms', 'countries' => [['country_code' => 'my', 'country_name' => __('Malaysia', 'auto-translate')],['country_code' => 'id', 'country_name' => __('Indonesia', 'auto-translate')],['country_code' => 'sg', 'country_name' => __('Singapore', 'auto-translate')],['country_code' => 'bn', 'country_name' => __('Brunei', 'auto-translate')],]],
    'ml' => ['lang_name' => __('Malayalam', 'auto-translate'), 'lang_code' => 'ml', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],]],
    'mt' => ['lang_name' => __('Maltese', 'auto-translate'), 'lang_code' => 'mt', 'countries' => [['country_code' => 'mt', 'country_name' => __('Malta', 'auto-translate')],]],
    'mi' => ['lang_name' => __('Maori', 'auto-translate'), 'lang_code' => 'mi', 'countries' => [['country_code' => 'nz', 'country_name' => __('New Zealand', 'auto-translate')],['country_code' => 'ck', 'country_name' => __('Cook Islands', 'auto-translate')],]],
    'mr' => ['lang_name' => __('Marathi', 'auto-translate'), 'lang_code' => 'mr', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],]],
    'mn' => ['lang_name' => __('Mongolian', 'auto-translate'), 'lang_code' => 'mn', 'countries' => [['country_code' => 'mn', 'country_name' => __('Mongolia', 'auto-translate')],]],
    'my' => ['lang_name' => __('Myanmar (Burmese)', 'auto-translate'), 'lang_code' => 'my', 'countries' => [['country_code' => 'mm', 'country_name' => __('Myanmar', 'auto-translate')],]],
    'ne' => ['lang_name' => __('Nepali', 'auto-translate'), 'lang_code' => 'ne', 'countries' => [['country_code' => 'np', 'country_name' => __('Nepal', 'auto-translate')],]],
    'no' => ['lang_name' => __('Norwegian', 'auto-translate'), 'lang_code' => 'no', 'countries' => [['country_code' => 'no', 'country_name' => __('Norway', 'auto-translate')],]],
    'ps' => ['lang_name' => __('Pashto', 'auto-translate'), 'lang_code' => 'ps', 'countries' => [['country_code' => 'af', 'country_name' => __('Afghanistan', 'auto-translate')],]],
    'fa' => ['lang_name' => __('Persian', 'auto-translate'), 'lang_code' => 'fa', 'countries' => [['country_code' => 'ir', 'country_name' => __('Iran', 'auto-translate')],]],
    'pl' => ['lang_name' => __('Polish', 'auto-translate'), 'lang_code' => 'pl', 'countries' => [['country_code' => 'pl', 'country_name' => __('Poland', 'auto-translate')],]],
    'pt' => ['lang_name' => __('Portuguese', 'auto-translate'), 'lang_code' => 'pt', 'countries' => [['country_code' => 'pt', 'country_name' => __('Portugal', 'auto-translate')],['country_code' => 'br', 'country_name' => __('Brazil', 'auto-translate')],['country_code' => 'mz', 'country_name' => __('Mozambique', 'auto-translate')],['country_code' => 'ao', 'country_name' => __('Angola', 'auto-translate')],]],
    'pa' => ['lang_name' => __('Punjabi', 'auto-translate'), 'lang_code' => 'pa', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],['country_code' => 'pk', 'country_name' => __('Pakistan', 'auto-translate')],]],
    'ro' => ['lang_name' => __('Romanian', 'auto-translate'), 'lang_code' => 'ro', 'countries' => [['country_code' => 'ro', 'country_name' => __('Romania', 'auto-translate')],['country_code' => 'md', 'country_name' => __('Moldova', 'auto-translate')],]],
    'ru' => ['lang_name' => __('Russian', 'auto-translate'), 'lang_code' => 'ru', 'countries' => [['country_code' => 'ru', 'country_name' => __('Russia', 'auto-translate')],['country_code' => 'kz', 'country_name' => __('Kazakhstan', 'auto-translate')],['country_code' => 'by', 'country_name' => __('Belarus', 'auto-translate')],['country_code' => 'kg', 'country_name' => __('Kyrgyzstan', 'auto-translate')],['country_code' => 'tj', 'country_name' => __('Tajikistan', 'auto-translate')],]],
    'sm' => ['lang_name' => __('Samoan', 'auto-translate'), 'lang_code' => 'sm', 'countries' => [['country_code' => 'ws', 'country_name' => __('Samoa', 'auto-translate')],]],
    'gd' => ['lang_name' => __('Scots Gaelic', 'auto-translate'), 'lang_code' => 'gd', 'countries' => [['country_code' => 'gb-sct', 'country_name' => __('Scotland', 'auto-translate')],]],
    'sr' => ['lang_name' => __('Serbian', 'auto-translate'), 'lang_code' => 'sr', 'countries' => [['country_code' => 'rs', 'country_name' => __('Serbia', 'auto-translate')],['country_code' => 'ba', 'country_name' => __('Bosnia and Herzegovina', 'auto-translate')],]],
    'st' => ['lang_name' => __('Sesotho', 'auto-translate'), 'lang_code' => 'st', 'countries' => [['country_code' => 'ls', 'country_name' => __('Lesotho', 'auto-translate')],['country_code' => 'za', 'country_name' => __('South Africa', 'auto-translate')],['country_code' => 'zw', 'country_name' => __('Zimbabwe', 'auto-translate')],]],
    'sn' => ['lang_name' => __('Shona', 'auto-translate'), 'lang_code' => 'sn', 'countries' => [['country_code' => 'zw', 'country_name' => __('Zimbabwe', 'auto-translate')],]],
    'sd' => ['lang_name' => __('Sindhi', 'auto-translate'), 'lang_code' => 'sd', 'countries' => [['country_code' => 'pk', 'country_name' => __('Pakistan', 'auto-translate')],]],
    'si' => ['lang_name' => __('Sinhala', 'auto-translate'), 'lang_code' => 'si', 'countries' => [['country_code' => 'lk', 'country_name' => __('Sri Lanka', 'auto-translate')],]],
    'sk' => ['lang_name' => __('Slovak', 'auto-translate'), 'lang_code' => 'sk', 'countries' => [['country_code' => 'sk', 'country_name' => __('Slovakia', 'auto-translate')],['country_code' => 'cz', 'country_name' => __('Czech Republic', 'auto-translate')],]],
    'sl' => ['lang_name' => __('Slovenian', 'auto-translate'), 'lang_code' => 'sl', 'countries' => [['country_code' => 'si', 'country_name' => __('Slovenia', 'auto-translate')],]],
    'so' => ['lang_name' => __('Somali', 'auto-translate'), 'lang_code' => 'so', 'countries' => [['country_code' => 'so', 'country_name' => __('Somalia', 'auto-translate')],['country_code' => 'dj', 'country_name' => __('Djibouti', 'auto-translate')],['country_code' => 'et', 'country_name' => __('Ethiopia', 'auto-translate')],]],
    'es' => ['lang_name' => __('Spanish', 'auto-translate'), 'lang_code' => 'es', 'countries' => [['country_code' => 'es', 'country_name' => __('Spain', 'auto-translate')],['country_code' => 'mx', 'country_name' => __('Mexico', 'auto-translate')],['country_code' => 'ar', 'country_name' => __('Argentina', 'auto-translate')],['country_code' => 'co', 'country_name' => __('Colombia', 'auto-translate')],['country_code' => 'pe', 'country_name' => __('Peru', 'auto-translate')],['country_code' => 'ec', 'country_name' => __('Ecuador', 'auto-translate')],['country_code' => 'bo', 'country_name' => __('Bolivia', 'auto-translate')],['country_code' => 'cl', 'country_name' => __('Chile', 'auto-translate')],['country_code' => 'gq', 'country_name' => __('Equatorial Guinea', 'auto-translate')],['country_code' => 'gt', 'country_name' => __('Guatemala', 'auto-translate')],['country_code' => 'cu', 'country_name' => __('Cuba', 'auto-translate')],['country_code' => 'do', 'country_name' => __('Dominican Republic', 'auto-translate')],['country_code' => 'hn', 'country_name' => __('Honduras', 'auto-translate')],['country_code' => 'py', 'country_name' => __('Paraguay', 'auto-translate')],['country_code' => 'sv', 'country_name' => __('El Salvador', 'auto-translate')],['country_code' => 'ni', 'country_name' => __('Nicaragua', 'auto-translate')],['country_code' => 'cr', 'country_name' => __('Costa Rica', 'auto-translate')],['country_code' => 'pa', 'country_name' => __('Panama', 'auto-translate')],['country_code' => 'uy', 'country_name' => __('Uruguay', 'auto-translate')],]],
    'su' => ['lang_name' => __('Sundanese', 'auto-translate'), 'lang_code' => 'su', 'countries' => [['country_code' => 'id', 'country_name' => __('Indonesia', 'auto-translate')],]],
    'sw' => ['lang_name' => __('Swahili', 'auto-translate'), 'lang_code' => 'sw', 'countries' => [['country_code' => 'tz', 'country_name' => __('Tanzania', 'auto-translate')],['country_code' => 'rw', 'country_name' => __('Rwanda', 'auto-translate')],['country_code' => 'ke', 'country_name' => __('Kenya', 'auto-translate')],['country_code' => 'ug', 'country_name' => __('Uganda', 'auto-translate')],]],
    'sv' => ['lang_name' => __('Swedish', 'auto-translate'), 'lang_code' => 'sv', 'countries' => [['country_code' => 'se', 'country_name' => __('Sweden', 'auto-translate')],['country_code' => 'fi', 'country_name' => __('Finland', 'auto-translate')],]],
    'tg' => ['lang_name' => __('Tajik', 'auto-translate'), 'lang_code' => 'tg', 'countries' => [['country_code' => 'tj', 'country_name' => __('Tajikistan', 'auto-translate')],]],
    'ta' => ['lang_name' => __('Tamil', 'auto-translate'), 'lang_code' => 'ta', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],['country_code' => 'lk', 'country_name' => __('Sri Lanka', 'auto-translate')],['country_code' => 'sg', 'country_name' => __('Singapore', 'auto-translate')],]],
    'te' => ['lang_name' => __('Telugu', 'auto-translate'), 'lang_code' => 'te', 'countries' => [['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],]],
    'th' => ['lang_name' => __('Thai', 'auto-translate'), 'lang_code' => 'th', 'countries' => [['country_code' => 'th', 'country_name' => __('Thailand', 'auto-translate')],]],
    'tr' => ['lang_name' => __('Turkish', 'auto-translate'), 'lang_code' => 'tr', 'countries' => [['country_code' => 'tr', 'country_name' => __('Turkey', 'auto-translate')],['country_code' => 'cy', 'country_name' => __('Cyprus', 'auto-translate')],]],
    'uk' => ['lang_name' => __('Ukrainian', 'auto-translate'), 'lang_code' => 'uk', 'countries' => [['country_code' => 'ua', 'country_name' => __('Ukraine', 'auto-translate')],]],
    'ur' => ['lang_name' => __('Urdu', 'auto-translate'), 'lang_code' => 'ur', 'countries' => [['country_code' => 'pk', 'country_name' => __('Pakistan', 'auto-translate')],['country_code' => 'in', 'country_name' => __('India', 'auto-translate')],]],
    'uz' => ['lang_name' => __('Uzbek', 'auto-translate'), 'lang_code' => 'uz', 'countries' => [['country_code' => 'uz', 'country_name' => __('Uzbekistan', 'auto-translate')],]],
    'vi' => ['lang_name' => __('Vietnamese', 'auto-translate'), 'lang_code' => 'vi', 'countries' => [['country_code' => 'vn', 'country_name' => __('Vietnam', 'auto-translate')],]],
    'cy' => ['lang_name' => __('Welsh', 'auto-translate'), 'lang_code' => 'cy', 'countries' => [['country_code' => 'gb-wls', 'country_name' => __('Wales', 'auto-translate')],]],
    'xh' => ['lang_name' => __('Xhosa', 'auto-translate'), 'lang_code' => 'xh', 'countries' => [['country_code' => 'za', 'country_name' => __('South Africa', 'auto-translate')],['country_code' => 'zw', 'country_name' => __('Zimbabwe', 'auto-translate')],]],
    'yi' => ['lang_name' => __('Yiddish', 'auto-translate'), 'lang_code' => 'yi', 'countries' => [['country_code' => 'il', 'country_name' => __('Israel', 'auto-translate')],]],
    'yo' => ['lang_name' => __('Yoruba', 'auto-translate'), 'lang_code' => 'yo', 'countries' => [['country_code' => 'ng', 'country_name' => __('Nigeria', 'auto-translate')],]],
    'zu' => ['lang_name' => __('Zulu', 'auto-translate'), 'lang_code' => 'zu', 'countries' => [['country_code' => 'za', 'country_name' => __('South Africa', 'auto-translate')],]],
];