<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'intrace' ),
	'categories' => array( 'intrace-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":1136,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/architecture-house-home-pool-ceiling-italy-599832-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":{"id":1119,"image":"' . esc_url( INTRACE_URI ) . 'assets/img/line.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"}},"opacity":"0.7","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"370","bottom":"300","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"243","bottom":"143","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"120"}}},"zIndex":{"Desktop":""}} -->
			<div class="section-wrapper" data-id="P6sVWZ"><script>var topP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};var bottomP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-P6sVWZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-91Fk0O","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-91Fk0O"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="91Fk0O"><script>var top91Fk0O = {"Desktop":{"point":"0","unit":"px"}};var bottom91Fk0O = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","type":1,"textAlign":{"Desktop":"center"},"color":{"r":173,"g":146,"b":113,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"72","unit":"px"},"Mobile":{"point":"29","unit":"px"},"Tablet":{"point":"56","unit":"px"}},"weight":"600","spacing":{"Desktop":"0.1","Mobile":"0.03"},"transform":"uppercase","decoration":"none","style":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-XvGz0E animated guten-element-hide desktop-fadeInLeft">Interior designs</h1>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-19Eyfa","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"48","unit":"px"}},"weight":"600","spacing":{"Desktop":"0.1","Mobile":"0.03"},"transform":"uppercase","decoration":"none","style":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-19Eyfa animated guten-element-hide desktop-fadeInRight">from the future</h1>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"View Portfolio","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"width":"1","type":"solid","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"300"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1","Mobile":"0.1"},"weight":"400","lineHeight":{"Desktop":{"point":"","unit":"px"}}},"hoverTextColor":{"r":24,"g":24,"b":24,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button animated guten-element-hide desktop-fadeInDown guten-button-sm" href="#"><span>View Portfolio</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
