<?php
/**
 * Gutenverse FAQ Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Section 4', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"776"},"gap":"no","elementId":"guten-OqBJa3","background":{"type":"default","image":{"Desktop":{"id":288,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-wood-vintage-texture-floor-wall-1173373-pxhere.com.webp"}},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":0,"g":42,"b":87,"a":1}},"opacity":"0.8","margin":{"Desktop":{},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}}}} -->
			<div class="section-wrapper" data-id="OqBJa3"><script>var topOqBJa3 = {"Desktop":{"point":"0","unit":"px"}};var bottomOqBJa3 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-OqBJa3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-PF1k7w","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-PF1k7w"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PF1k7w"><script>var topPF1k7w = {"Desktop":{"point":"0","unit":"px"}};var bottomPF1k7w = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-OBWF5r","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"},"Tablet":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"50","left":"50"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-OBWF5r animated guten-element-hide desktop-fadeInUp">Take a Break &amp; Checkout Our<br>Top Destinations</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/buttons {"elementId":"guten-FICKir","alignButtons":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{}}} -->
			<div class="guten-element guten-buttons horizontal guten-FICKir"><!-- wp:gutenverse/button {"elementId":"guten-qBi6qO","content":"See Packages","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"color":{"r":242,"g":139,"b":56,"a":1},"type":"solid","width":"3"}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-qBi6qO"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>See Packages</span></a></div>
			<!-- /wp:gutenverse/button -->

			<!-- wp:gutenverse/button {"elementId":"guten-P3ztSM","content":"Discover More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{}},"all":{"type":"solid","width":"3","color":{"r":242,"g":139,"b":56,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{}},"all":{"type":"solid","width":"3","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":0,"g":21,"b":68,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-P3ztSM"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Discover More</span></a></div>
			<!-- /wp:gutenverse/button --></div>
			<!-- /wp:gutenverse/buttons --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
