<?php
/**
 * Gutenverse Home Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 2', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-Hd5S49","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
			<div class="section-wrapper" data-id="Hd5S49"><script>var topHd5S49 = {"Desktop":{"point":"0","unit":"px"}};var bottomHd5S49 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Hd5S49 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Mobile":null},"elementId":"guten-HKaTyk","margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HKaTyk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HKaTyk"><script>var topHKaTyk = {"Desktop":{"point":"0","unit":"px"}};var bottomHKaTyk = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Sfrfx7","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-Sfrfx7 animated guten-element-hide desktop-fadeInLeft">Popular Destination</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-UAAgvn","color":{"r":238,"g":239,"b":243,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"96","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"96","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.031"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-69","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-72"}},"Mobile":{"unit":"px","dimension":{"top":"-66"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-UAAgvn animated guten-element-hide desktop-fadeInLeft">Popular</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-3w07is","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-19","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"-35","bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"40"}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-text-editor guten-3w07is animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-vV2TpX","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vV2TpX"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vV2TpX"><script>var topvV2TpX = {"Desktop":{"point":"0","unit":"px"}};var bottomvV2TpX = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-lrpuBO","content":"Discover more","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"padding":{"Desktop":[],"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-lrpuBO"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Discover more</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
