<?php
/**
 * Gutenverse FAQ Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-MA14S5","margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"70"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}}} -->
			<div class="section-wrapper" data-id="MA14S5"><script>var topMA14S5 = {"Desktop":{"point":"0","unit":"px"}};var bottomMA14S5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-MA14S5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-3fQVwF","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3fQVwF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3fQVwF"><script>var top3fQVwF = {"Desktop":{"point":"0","unit":"px"}};var bottom3fQVwF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4Uhwo5","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="4Uhwo5"><script>var top4Uhwo5 = {"Desktop":{"point":"0","unit":"px"}};var bottom4Uhwo5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4Uhwo5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-A4U61B","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-A4U61B"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A4U61B"><script>var topA4U61B = {"Desktop":{"point":"0","unit":"px"}};var bottomA4U61B = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-tLcMwv","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-tLcMwv animated guten-element-hide desktop-fadeInLeft">Reservation</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/accordions {"elementId":"guten-mTVb3w","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right","iconColor":{"r":242,"g":139,"b":56,"a":1},"iconActiveColor":{"r":242,"g":139,"b":56,"a":1},"titleBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"titleTextColor":{"r":1,"g":22,"b":51,"a":1},"titleActiveColor":{"r":1,"g":22,"b":51,"a":1},"titleTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":[]},"contentBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"contentTextColor":{"r":111,"g":116,"b":126,"a":1},"contentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"40"}},"Tablet":[],"Mobile":[]},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":""}},"Tablet":[]},"contentBackgroundColorActive":{"r":255,"g":255,"b":255,"a":1},"contentTextColorActive":{"r":111,"g":116,"b":126,"a":1},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"titleBackgroundActiveColor":{"r":255,"g":255,"b":255,"a":1},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}}} -->
			<div class="guten-element guten-accordions guten-mTVb3w animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/accordion {"elementId":"guten-PhsjkV","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Do i have to make reservation?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->

			<!-- wp:gutenverse/accordion {"elementId":"guten-c35H3u","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What are your terms and conditions?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->

			<!-- wp:gutenverse/accordion {"elementId":"guten-YDeh1F","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Where do I find my trip notes?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion --></div>
			<!-- /wp:gutenverse/accordions --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-OGQZyp","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OGQZyp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OGQZyp"><script>var topOGQZyp = {"Desktop":{"point":"0","unit":"px"}};var bottomOGQZyp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-icHKKp","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="icHKKp"><script>var topicHKKp = {"Desktop":{"point":"0","unit":"px"}};var bottomicHKKp = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-icHKKp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-jz00ZB","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"10"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jz00ZB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jz00ZB"><script>var topjz00ZB = {"Desktop":{"point":"0","unit":"px"}};var bottomjz00ZB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XSy0fh","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-XSy0fh animated guten-element-hide desktop-fadeInRight">Preparation</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/accordions {"elementId":"guten-XG5fXG","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right","iconColor":{"r":242,"g":139,"b":56,"a":1},"iconActiveColor":{"r":242,"g":139,"b":56,"a":1},"titleBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"titleTextColor":{"r":1,"g":22,"b":51,"a":1},"titleActiveColor":{"r":1,"g":22,"b":51,"a":1},"titleTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":[]},"contentBackgroundColor":{"r":255,"g":255,"b":255,"a":1},"contentTextColor":{"r":111,"g":116,"b":126,"a":1},"contentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","left":"20","right":"40"}},"Tablet":[],"Mobile":[]},"accordionBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"all":{"type":"none","color":""}},"titleBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"contentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":""}},"Tablet":[]},"contentBackgroundColorActive":{"r":255,"g":255,"b":255,"a":1},"contentTextColorActive":{"r":111,"g":116,"b":126,"a":1},"contentBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}},"titleBackgroundActiveColor":{"r":255,"g":255,"b":255,"a":1},"titleBorderActive":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":231,"g":235,"b":240,"a":1}}}} -->
			<div class="guten-element guten-accordions guten-XG5fXG animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/accordion {"elementId":"guten-OsaCC4","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What do i need to bring?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->

			<!-- wp:gutenverse/accordion {"elementId":"guten-TCo3EF","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">What are your terms and conditions?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion -->

			<!-- wp:gutenverse/accordion {"elementId":"guten-A4BRVP","iconOpen":"fas fa-angle-up","iconClosed":"fas fa-angle-right"} -->
			<div class="accordion-item"><div class="accordion-heading"><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-angle-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-angle-right"></i></span></div><span class="accordion-text">Where do I find my trip notes?</span></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
			<!-- /wp:paragraph --></div></div></div>
			<!-- /wp:gutenverse/accordion --></div>
			<!-- /wp:gutenverse/accordions --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
