<?php
/**
 * Gutenverse Packages Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Packages Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-fVTnrP","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"30","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"80"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
			<div class="section-wrapper" data-id="fVTnrP"><script>var topfVTnrP = {"Desktop":{"point":"0","unit":"px"}};var bottomfVTnrP = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-fVTnrP animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-oEHvu9","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-oEHvu9 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="oEHvu9"><script>var topoEHvu9 = {"Desktop":{"point":"0","unit":"px"}};var bottomoEHvu9 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-5nAwb4","imgSrc":{"media":{"imageId":217,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/japan-flower-spring-blossom-cherry-blossom-plant-1593208-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/japan-flower-spring-blossom-cherry-blossom-plant-1593208-pxhere.com-300x200.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/japan-flower-spring-blossom-cherry-blossom-plant-1593208-pxhere.com.webp","height":614,"width":920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"232","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-5nAwb4"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/japan-flower-spring-blossom-cherry-blossom-plant-1593208-pxhere.com.webp" height="614" width="920"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-dU0jcA","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="dU0jcA"><script>var topdU0jcA = {"Desktop":{"point":"0","unit":"px"}};var bottomdU0jcA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-dU0jcA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-pW9eCF","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pW9eCF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pW9eCF"><script>var toppW9eCF = {"Desktop":{"point":"0","unit":"px"}};var bottompW9eCF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8k1cK5","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-8k1cK5">Japan</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-LNDeoP","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LNDeoP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LNDeoP"><script>var topLNDeoP = {"Desktop":{"point":"0","unit":"px"}};var bottomLNDeoP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-2vc1dm","alignText":{"Desktop":"flex-end"},"text":"$750 ","focusText":"/3days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-2vc1dm"><div class="heading-section "><h2 class="heading-title">$750 <span class="heading-focus">/3days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-BmNdp7","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-BmNdp7"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-zpDxdu","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="zpDxdu"><script>var topzpDxdu = {"Desktop":{"point":"0","unit":"px"}};var bottomzpDxdu = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-zpDxdu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-IFDhnm","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-IFDhnm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="IFDhnm"><script>var topIFDhnm = {"Desktop":{"point":"0","unit":"px"}};var bottomIFDhnm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-G8PeZG","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-G8PeZG"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-yU9uDG"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-yU9uDG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yU9uDG"><script>var topyU9uDG = {"Desktop":{"point":"0","unit":"px"}};var bottomyU9uDG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-91Rz9f","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-91Rz9f"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.37,"Tablet":50,"Mobile":null},"elementId":"guten-GOsQT3","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-GOsQT3 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GOsQT3"><script>var topGOsQT3 = {"Desktop":{"point":"0","unit":"px"}};var bottomGOsQT3 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-m4ZVVt","imgSrc":{"media":{"imageId":218,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-night-city-eiffel-tower-paris-1046619-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":169,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-night-city-eiffel-tower-paris-1046619-pxhere.com-300x169.webp","orientation":"landscape"},"large":{"height":576,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-night-city-eiffel-tower-paris-1046619-pxhere.com-1024x576.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-night-city-eiffel-tower-paris-1046619-pxhere.com.webp","height":1080,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"371","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"232","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-m4ZVVt"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-night-city-eiffel-tower-paris-1046619-pxhere.com.webp" height="1080" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-S9AYKe","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}},"Mobile":{}}} -->
			<div class="section-wrapper" data-id="S9AYKe"><script>var topS9AYKe = {"Desktop":{"point":"0","unit":"px"}};var bottomS9AYKe = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-S9AYKe layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":40.41},"elementId":"guten-jPHB0b","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jPHB0b"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jPHB0b"><script>var topjPHB0b = {"Desktop":{"point":"0","unit":"px"}};var bottomjPHB0b = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-jg09sI","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-jg09sI">France</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-SNajVI","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SNajVI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SNajVI"><script>var topSNajVI = {"Desktop":{"point":"0","unit":"px"}};var bottomSNajVI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-EGY0sI","alignText":{"Desktop":"flex-end"},"text":"$1000 ","focusText":"/2days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-EGY0sI"><div class="heading-section "><h2 class="heading-title">$1000 <span class="heading-focus">/2days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-Wl7CPf","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-Wl7CPf"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4VznoB","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="4VznoB"><script>var top4VznoB = {"Desktop":{"point":"0","unit":"px"}};var bottom4VznoB = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4VznoB layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-gl4TuW","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-gl4TuW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="gl4TuW"><script>var topgl4TuW = {"Desktop":{"point":"0","unit":"px"}};var bottomgl4TuW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-pSLI7l","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-pSLI7l"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-DEyvUL"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DEyvUL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DEyvUL"><script>var topDEyvUL = {"Desktop":{"point":"0","unit":"px"}};var bottomDEyvUL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-aUo8cw","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-aUo8cw"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":100,"Mobile":null},"elementId":"guten-A6zeR7","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","top":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-A6zeR7 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A6zeR7"><script>var topA6zeR7 = {"Desktop":{"point":"0","unit":"px"}};var bottomA6zeR7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-skbeQr","imgSrc":{"media":{"imageId":219,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-bridge-skyline-building-city-748076-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-bridge-skyline-building-city-748076-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-bridge-skyline-building-city-748076-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-bridge-skyline-building-city-748076-pxhere.com.webp","height":1014,"width":1520,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"370","unit":"px"},"Tablet":{"point":"754","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"488","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-skbeQr"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-sunset-bridge-skyline-building-city-748076-pxhere.com.webp" height="1014" width="1520"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-JIBfUA","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="section-wrapper" data-id="JIBfUA"><script>var topJIBfUA = {"Desktop":{"point":"0","unit":"px"}};var bottomJIBfUA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-JIBfUA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-zWB9AA","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zWB9AA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zWB9AA"><script>var topzWB9AA = {"Desktop":{"point":"0","unit":"px"}};var bottomzWB9AA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-LL9JOq","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Tablet":{"point":"20","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-LL9JOq">England</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-RzYYRD","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"flex-end","Mobile":"flex-start"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RzYYRD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RzYYRD"><script>var topRzYYRD = {"Desktop":{"point":"0","unit":"px"}};var bottomRzYYRD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-eWRM01","alignText":{"Desktop":"flex-end"},"text":"$800 ","focusText":"/2days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-eWRM01"><div class="heading-section "><h2 class="heading-title">$800 <span class="heading-focus">/2days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-qLx2RY","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-qLx2RY"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-FEJchh","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="FEJchh"><script>var topFEJchh = {"Desktop":{"point":"0","unit":"px"}};var bottomFEJchh = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-FEJchh layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-57l5N0","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-57l5N0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="57l5N0"><script>var top57l5N0 = {"Desktop":{"point":"0","unit":"px"}};var bottom57l5N0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-chkvRf","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-chkvRf"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Tablet":null,"Mobile":100},"elementId":"guten-t9Wfv2","margin":{"Tablet":{}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-t9Wfv2"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="t9Wfv2"><script>var topt9Wfv2 = {"Desktop":{"point":"0","unit":"px"}};var bottomt9Wfv2 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-xDy3Bv","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-xDy3Bv"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
