<?php
/**
 * Gutenverse Destination Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Destination Section 2', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-jGzT2W","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="jGzT2W"><script>var topjGzT2W = {"Desktop":{"point":"0","unit":"px"}};var bottomjGzT2W = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-jGzT2W layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-Hfvgjy","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Hfvgjy animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Hfvgjy"><script>var topHfvgjy = {"Desktop":{"point":"0","unit":"px"}};var bottomHfvgjy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-v8QKdj","imgSrc":{"media":{"imageId":56,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":684,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com-1024x684.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com.webp","height":801,"width":1200,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"733","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"485","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-v8QKdj"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-rock-ocean-107831-pxhere.com.webp" height="801" width="1200"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-xnz2Y1","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="xnz2Y1"><script>var topxnz2Y1 = {"Desktop":{"point":"0","unit":"px"}};var bottomxnz2Y1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-xnz2Y1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-rBUKcy"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-rBUKcy"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rBUKcy"><script>var toprBUKcy = {"Desktop":{"point":"0","unit":"px"}};var bottomrBUKcy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SqMGY4","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-SqMGY4">Labuan Bajo, NTT</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-GSYiqY","horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-GSYiqY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GSYiqY"><script>var topGSYiqY = {"Desktop":{"point":"0","unit":"px"}};var bottomGSYiqY = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-hlw9eF","type":6,"textAlign":{"Tablet":"right","Mobile":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-hlw9eF">$249.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-BxNS8h","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-BxNS8h"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-UfoMP5","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="UfoMP5"><script>var topUfoMP5 = {"Desktop":{"point":"0","unit":"px"}};var bottomUfoMP5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-UfoMP5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-0vAAD6","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-0vAAD6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0vAAD6"><script>var top0vAAD6 = {"Desktop":{"point":"0","unit":"px"}};var bottom0vAAD6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-WNJjQP","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-WNJjQP"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-Eb4qfJ"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Eb4qfJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Eb4qfJ"><script>var topEb4qfJ = {"Desktop":{"point":"0","unit":"px"}};var bottomEb4qfJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-fqObuP","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"22"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-fqObuP"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-3iy2Tp","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3iy2Tp animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3iy2Tp"><script>var top3iy2Tp = {"Desktop":{"point":"0","unit":"px"}};var bottom3iy2Tp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-ueyqxi","imgSrc":{"media":{"imageId":67,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":204,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com-300x204.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com.webp","height":681,"width":1000,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-ueyqxi"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/landscape-nature-outdoor-mountain-field-farm-1349556-pxhere.com.webp" height="681" width="1000"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-uOrvx1","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="uOrvx1"><script>var topuOrvx1 = {"Desktop":{"point":"0","unit":"px"}};var bottomuOrvx1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-uOrvx1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"elementId":"guten-PPgYiU"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-PPgYiU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PPgYiU"><script>var topPPgYiU = {"Desktop":{"point":"0","unit":"px"}};var bottomPPgYiU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-UhBvSH","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-UhBvSH">Rice Terraces, Bali</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"elementId":"guten-MnpExD","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-MnpExD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MnpExD"><script>var topMnpExD = {"Desktop":{"point":"0","unit":"px"}};var bottomMnpExD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-6RyYvU","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-6RyYvU">$299.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-mjNkV1","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-mjNkV1"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-GoTRW5","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="GoTRW5"><script>var topGoTRW5 = {"Desktop":{"point":"0","unit":"px"}};var bottomGoTRW5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-GoTRW5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-XeawVq","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-XeawVq"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XeawVq"><script>var topXeawVq = {"Desktop":{"point":"0","unit":"px"}};var bottomXeawVq = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-Xy1xF0","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-Xy1xF0"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-8yzJk3"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8yzJk3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8yzJk3"><script>var top8yzJk3 = {"Desktop":{"point":"0","unit":"px"}};var bottom8yzJk3 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-dGeAbw","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-dGeAbw"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50},"elementId":"guten-0lhJNz","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-0lhJNz animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0lhJNz"><script>var top0lhJNz = {"Desktop":{"point":"0","unit":"px"}};var bottom0lhJNz = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-reK5GV","imgSrc":{"media":{"imageId":68,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-300x225.webp","orientation":"landscape"},"large":{"height":768,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com-1024x768.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com.webp","height":1125,"width":1500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-reK5GV"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-stone-travel-religion-1048044-pxhere.com.webp" height="1125" width="1500"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-roy7ls","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="roy7ls"><script>var toproy7ls = {"Desktop":{"point":"0","unit":"px"}};var bottomroy7ls = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-roy7ls layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"elementId":"guten-FlHd45"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-FlHd45"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FlHd45"><script>var topFlHd45 = {"Desktop":{"point":"0","unit":"px"}};var bottomFlHd45 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ef8lC8","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-ef8lC8">Prambanan, Yogya</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"elementId":"guten-1vONrr","verticalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1vONrr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1vONrr"><script>var top1vONrr = {"Desktop":{"point":"0","unit":"px"}};var bottom1vONrr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-cNPScD","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-cNPScD">$199.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-yFW8QX","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-yFW8QX"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-2RV4Gx","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="2RV4Gx"><script>var top2RV4Gx = {"Desktop":{"point":"0","unit":"px"}};var bottom2RV4Gx = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-2RV4Gx layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-1g1wQT","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1g1wQT"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1g1wQT"><script>var top1g1wQT = {"Desktop":{"point":"0","unit":"px"}};var bottom1g1wQT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-4WdYJJ","title":"","starIcon":"default","rating":"5","total":"5","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="guten-element guten-star-rating guten-4WdYJJ"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-t0yUht"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-t0yUht"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="t0yUht"><script>var topt0yUht = {"Desktop":{"point":"0","unit":"px"}};var bottomt0yUht = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-7gDWjV","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-7gDWjV"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
