<?php
/**
 * Gutenverse About Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 1', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-ZpUOCL","margin":{"Desktop":{},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"0","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"0"}}}} -->
			<div class="section-wrapper" data-id="ZpUOCL"><script>var topZpUOCL = {"Desktop":{"point":"0","unit":"px"}};var bottomZpUOCL = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ZpUOCL layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-Trv65f","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Trv65f"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Trv65f"><script>var topTrv65f = {"Desktop":{"point":"0","unit":"px"}};var bottomTrv65f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-eU3PSG","imgSrc":{"media":{"imageId":195,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":199,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-300x199.webp","orientation":"landscape"},"large":{"height":680,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com-1024x680.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com.webp","height":1275,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"583","unit":"px"},"Tablet":{"point":"807","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"203","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{}}},"align":{"Desktop":"left","Tablet":"left"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-eU3PSG animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/mobile-hand-screen-apple-ipad-restaurant-1234397-pxhere.com.webp" height="1275" width="1920"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-ub70oE","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"40"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ub70oE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ub70oE"><script>var topub70oE = {"Desktop":{"point":"0","unit":"px"}};var bottomub70oE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-adfs0e","textAlign":{"Desktop":"left"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"35.2","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"600"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-adfs0e animated guten-element-hide desktop-fadeInRight">Get 100% Satisfaction With<br>Our Service</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-qVZetJ","textAlign":{"Desktop":"left"},"color":{"r":238,"g":239,"b":243,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"96","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"96","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-19","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-117"}},"Mobile":{"unit":"px","dimension":{"top":"-68"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-qVZetJ animated guten-element-hide desktop-fadeInRight">About</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-OBXPHu","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
			<div class="guten-element gutenverse-text-editor guten-OBXPHu animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed to eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-i9v5Ws","content":"Read More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}}} -->
			<div class="guten-element guten-button-wrapper guten-i9v5Ws"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Read More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
