<?php
/**
 * Gutenverse Contact Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Section 1', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170","Mobile":"1170"},"gap":"no","elementId":"guten-2cw8B7","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"60","left":"0"}}},"zIndex":{"Desktop":"2"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":false}} -->
			<div class="section-wrapper" data-id="2cw8B7"><script>var top2cw8B7 = {"Desktop":{"point":"0","unit":"px"}};var bottom2cw8B7 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-2cw8B7 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":100},"elementId":"guten-tCwytO","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"40"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-tCwytO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tCwytO"><script>var toptCwytO = {"Desktop":{"point":"0","unit":"px"}};var bottomtCwytO = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-3kS4kk","textAlign":{"Tablet":"center","Desktop":"left"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"20","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"1","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-78","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"9","bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-3kS4kk animated guten-element-hide desktop-fadeInLeft">Get In Touch</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-aMPUWb","textAlign":{"Desktop":"left","Tablet":"center","Mobile":"center"},"color":{"r":238,"g":239,"b":243,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"96","unit":"px"},"Mobile":{"point":"36","unit":"px"},"Tablet":{"point":"80","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0","Tablet":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-450","right":"","bottom":"","left":"13"}},"Tablet":{"unit":"px","dimension":{"top":"-47","right":"","left":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"-26","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningAlign":{"Tablet":"center"},"positioningLocation":"absolute","positioningLeft":{"Tablet":{"point":"0","unit":"px"},"Mobile":{"point":"0","unit":"px"},"Desktop":{"point":"-20","unit":"px"}},"positioningRight":{"Tablet":{"point":"0","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningTop":{"Tablet":{"point":"0","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-aMPUWb animated guten-element-hide desktop-fadeInLeft">Contact</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-bwmK4G","alignment":{"Tablet":"center"},"textColor":{"r":121,"g":130,"b":144,"a":1},"typography":{"size":{"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Desktop":{"point":"16","unit":"px"}},"font":{"label":"Heebo","value":"Heebo","type":"google"},"lineHeight":{"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"21","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"-11","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"65","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"8","bottom":"0","left":"8"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-text-editor guten-bwmK4G animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7z09Io","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":[]}} -->
			<div class="section-wrapper" data-id="7z09Io"><script>var top7z09Io = {"Desktop":{"point":"0","unit":"px"}};var bottom7z09Io = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-7z09Io layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-Ol0DVU","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Ol0DVU animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ol0DVU"><script>var topOl0DVU = {"Desktop":{"point":"0","unit":"px"}};var bottomOl0DVU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-BRP6ho","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"400"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-BRP6ho">Ubud, Bali</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-YHRH4Z","spaceBetween":{"Tablet":"3"},"iconColor":{"r":242,"g":139,"b":56,"a":1},"iconColorHover":{"r":242,"g":139,"b":56,"a":1},"textColor":{"r":111,"g":116,"b":126,"a":1},"textColorHover":{"r":111,"g":116,"b":126,"a":1},"textIndent":{"Desktop":"10","Tablet":""},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[]},"padding":{"Mobile":[],"Tablet":[]}} -->
			<div class="guten-element guten-icon-list guten-YHRH4Z"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Wv7R8E"} -->
			<div class="guten-element guten-icon-list-item guten-Wv7R8E"><a id="guten-Wv7R8E"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 361 154874</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-tnbaqT"} -->
			<div class="guten-element guten-icon-list-item guten-tnbaqT"><a id="guten-tnbaqT"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-mjcFgP"} -->
			<div class="guten-element guten-icon-list-item guten-mjcFgP"><a id="guten-mjcFgP"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Raya Ubud No.88, Bali 80571</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-UwNgcv","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-UwNgcv animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UwNgcv"><script>var topUwNgcv = {"Desktop":{"point":"0","unit":"px"}};var bottomUwNgcv = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-1VG7VR","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"400"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-1VG7VR">Denpasar, Bali</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-GaPV06","spaceBetween":{"Tablet":"3"},"iconColor":{"r":242,"g":139,"b":56,"a":1},"iconColorHover":{"r":242,"g":139,"b":56,"a":1},"textColor":{"r":111,"g":116,"b":126,"a":1},"textColorHover":{"r":111,"g":116,"b":126,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
			<div class="guten-element guten-icon-list guten-GaPV06"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-2W2WEJ"} -->
			<div class="guten-element guten-icon-list-item guten-2W2WEJ"><a id="guten-2W2WEJ"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 361 154874</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-GDnVqE"} -->
			<div class="guten-element guten-icon-list-item guten-GDnVqE"><a id="guten-GDnVqE"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-OT4zTr"} -->
			<div class="guten-element guten-icon-list-item guten-OT4zTr"><a id="guten-OT4zTr"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Niti Mandala, Renon, Bali 80225</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"width":{"Desktop":1140,"Tablet":"768","Mobile":"320"},"isChild":true,"gap":"no","elementId":"guten-k5uquA","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]}} -->
			<div class="section-wrapper" data-id="k5uquA"><script>var topk5uquA = {"Desktop":{"point":"0","unit":"px"}};var bottomk5uquA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-k5uquA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-lQPNC0","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lQPNC0 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lQPNC0"><script>var toplQPNC0 = {"Desktop":{"point":"0","unit":"px"}};var bottomlQPNC0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-xOpl0X","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"400"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-xOpl0X">Kuta, Bali</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-T5tEuI","spaceBetween":{"Tablet":"3"},"iconColor":{"r":242,"g":139,"b":56,"a":1},"iconColorHover":{"r":242,"g":139,"b":56,"a":1},"textColor":{"r":111,"g":116,"b":126,"a":1},"textColorHover":{"r":111,"g":116,"b":126,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":[]}} -->
			<div class="guten-element guten-icon-list guten-T5tEuI"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-HWDHlL"} -->
			<div class="guten-element guten-icon-list-item guten-HWDHlL"><a id="guten-HWDHlL"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 361 154874</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-eiHcQ0"} -->
			<div class="guten-element guten-icon-list-item guten-eiHcQ0"><a id="guten-eiHcQ0"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-gGiAa2"} -->
			<div class="guten-element guten-icon-list-item guten-gGiAa2"><a id="guten-gGiAa2"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Sunset Road No. 815, Bali</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null},"elementId":"guten-BavNK2","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-BavNK2 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BavNK2"><script>var topBavNK2 = {"Desktop":{"point":"0","unit":"px"}};var bottomBavNK2 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-hN0SNo","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"400"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-hN0SNo">Tabanan, Bali</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-ttQilG","spaceBetween":{"Tablet":"3"},"iconColor":{"r":242,"g":139,"b":56,"a":1},"iconColorHover":{"r":242,"g":139,"b":56,"a":1},"textColor":{"r":111,"g":116,"b":126,"a":1},"textColorHover":{"r":111,"g":116,"b":126,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
			<div class="guten-element guten-icon-list guten-ttQilG"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-COsHnt"} -->
			<div class="guten-element guten-icon-list-item guten-COsHnt"><a id="guten-COsHnt"><i class="fas fa-phone-alt"></i><span class="list-text ">(+62) 361 154874</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-7cLN95"} -->
			<div class="guten-element guten-icon-list-item guten-7cLN95"><a id="guten-7cLN95"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-csFN6I"} -->
			<div class="guten-element guten-icon-list-item guten-csFN6I"><a id="guten-csFN6I"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Tendean, Kediri, Bali</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":100},"elementId":"guten-CWslS9","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"boxShadow":{"color":"","horizontal":"0","vertical":"0","blur":"0"},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-CWslS9 animated guten-element-hide slow desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CWslS9"><script>var topCWslS9 = {"Desktop":{"point":"0","unit":"px"}};var bottomCWslS9 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-TZtAs1","formId":{"label":"Message","value":367},"background":{"type":"default"},"border":{"radius":{"Mobile":[],"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none","width":"","color":""}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"35","right":"35","bottom":"35","left":"35"}},"Tablet":[]},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-TZtAs1 animated guten-element-hide desktop-fadeInUp" data-form-id="367"><!-- wp:gutenverse/form-input-text {"elementId":"guten-3bX8Ol","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperColor":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":195,"g":199,"b":206,"a":1}},"inputTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-3bX8Ol hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text -->

			<!-- wp:gutenverse/form-input-email {"elementId":"guten-oXyIca","showLabel":false,"showHelper":false,"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":195,"g":199,"b":206,"a":1}},"inputTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
			<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-oXyIca hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-email -->

			<!-- wp:gutenverse/form-input-text {"elementId":"guten-pK01mc","showLabel":false,"inputPlaceholder":"Subject","showHelper":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":195,"g":199,"b":206,"a":1}},"inputTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-pK01mc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text -->

			<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-aM3jG3","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"160"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"r":195,"g":199,"b":206,"a":1}},"inputTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Mobile":[]},"all":{"type":"solid","color":{"r":237,"g":237,"b":237,"a":1}}}} -->
			<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-aM3jG3 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-textarea -->

			<!-- wp:gutenverse/form-input-submit {"elementId":"guten-8fxoMT","content":"Send Message","buttonWidth":{"Desktop":"100","Tablet":"35","Mobile":"76"},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"alignButton":{"Desktop":"center","Tablet":"flex-start"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}}} -->
			<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-8fxoMT"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
			<!-- /wp:gutenverse/form-input-submit --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
