<?php
/**
 * Gutenverse Destination Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Destination Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-HN14DV","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Tablet":{"unit":"px","dimension":{"bottom":"80"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
			<div class="section-wrapper" data-id="HN14DV"><script>var topHN14DV = {"Desktop":{"point":"0","unit":"px"}};var bottomHN14DV = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HN14DV animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100},"elementId":"guten-zYj6AY","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zYj6AY animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zYj6AY"><script>var topzYj6AY = {"Desktop":{"point":"0","unit":"px"}};var bottomzYj6AY = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-MRKcMe","imgSrc":{"media":{"imageId":70,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com.webp","height":1001,"width":1500,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"733","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"488","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-MRKcMe"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com.webp" height="1001" width="1500"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-lHQU5p","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="lHQU5p"><script>var toplHQU5p = {"Desktop":{"point":"0","unit":"px"}};var bottomlHQU5p = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-lHQU5p layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-vCaCmD"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vCaCmD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vCaCmD"><script>var topvCaCmD = {"Desktop":{"point":"0","unit":"px"}};var bottomvCaCmD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-AYA5PF","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-AYA5PF">Borobudur, Java</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-96aNBR","horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-96aNBR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="96aNBR"><script>var top96aNBR = {"Desktop":{"point":"0","unit":"px"}};var bottom96aNBR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Xpfyi1","type":6,"textAlign":{"Tablet":"right","Mobile":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-Xpfyi1">$249.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-6GDZit","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-6GDZit"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-SEYXqO","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="SEYXqO"><script>var topSEYXqO = {"Desktop":{"point":"0","unit":"px"}};var bottomSEYXqO = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-SEYXqO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-A8xNl0","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-A8xNl0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="A8xNl0"><script>var topA8xNl0 = {"Desktop":{"point":"0","unit":"px"}};var bottomA8xNl0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-X4qrIe","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-X4qrIe"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-AOZMVp"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-AOZMVp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AOZMVp"><script>var topAOZMVp = {"Desktop":{"point":"0","unit":"px"}};var bottomAOZMVp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-kxAcJY","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-kxAcJY"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-DEa1DZ","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DEa1DZ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DEa1DZ"><script>var topDEa1DZ = {"Desktop":{"point":"0","unit":"px"}};var bottomDEa1DZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-tn2cFs","imgSrc":{"media":{"imageId":287,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":225,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-300x225.webp","orientation":"landscape"},"large":{"height":768,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com-1024x768.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com.webp","height":1920,"width":2560,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-tn2cFs"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-ocean-horizon-10686-pxhere.com.webp" height="1920" width="2560"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7k9VNZ","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="7k9VNZ"><script>var top7k9VNZ = {"Desktop":{"point":"0","unit":"px"}};var bottom7k9VNZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-7k9VNZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"elementId":"guten-qgnw1g"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-qgnw1g"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qgnw1g"><script>var topqgnw1g = {"Desktop":{"point":"0","unit":"px"}};var bottomqgnw1g = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-mO6Lqt","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-mO6Lqt">Gili Meno, NTB</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"elementId":"guten-pQncM1","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pQncM1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pQncM1"><script>var toppQncM1 = {"Desktop":{"point":"0","unit":"px"}};var bottompQncM1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-X4Wxn6","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-X4Wxn6">$299.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-S4ExAX","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-S4ExAX"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-0Remgi","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="0Remgi"><script>var top0Remgi = {"Desktop":{"point":"0","unit":"px"}};var bottom0Remgi = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-0Remgi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-OPYblc","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OPYblc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OPYblc"><script>var topOPYblc = {"Desktop":{"point":"0","unit":"px"}};var bottomOPYblc = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-zAPoeF","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-zAPoeF"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-QKRp5e"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-QKRp5e"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QKRp5e"><script>var topQKRp5e = {"Desktop":{"point":"0","unit":"px"}};var bottomQKRp5e = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-toCluG","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"12","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-toCluG"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-uhvBAf","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":0.82},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-uhvBAf animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="uhvBAf"><script>var topuhvBAf = {"Desktop":{"point":"0","unit":"px"}};var bottomuhvBAf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-gGh3tX","imgSrc":{"media":{"imageId":289,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":178,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-300x178.webp","orientation":"landscape"},"large":{"height":609,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com-1024x609.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com.webp","height":1142,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"352","unit":"px"},"Mobile":{"point":"313","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"233","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-gGh3tX"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/sunrise-sky-dawn-mountain-afterglow-highland-1432045-pxhere.com.webp" height="1142" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-VJoH1F","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="VJoH1F"><script>var topVJoH1F = {"Desktop":{"point":"0","unit":"px"}};var bottomVJoH1F = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-VJoH1F layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":50},"elementId":"guten-BIWISW"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-BIWISW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BIWISW"><script>var topBIWISW = {"Desktop":{"point":"0","unit":"px"}};var bottomBIWISW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q7y6Mz","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-q7y6Mz">Bromo, Java</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":50},"elementId":"guten-vnYmId","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vnYmId"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vnYmId"><script>var topvnYmId = {"Desktop":{"point":"0","unit":"px"}};var bottomvnYmId = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-T8XXwJ","type":6,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-T8XXwJ">$199.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-N2NPs9","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-N2NPs9"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-cle9by","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="cle9by"><script>var topcle9by = {"Desktop":{"point":"0","unit":"px"}};var bottomcle9by = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-cle9by layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-AAKvmC","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-AAKvmC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AAKvmC"><script>var topAAKvmC = {"Desktop":{"point":"0","unit":"px"}};var bottomAAKvmC = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-cYY9o5","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-cYY9o5"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-HlR4fx"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HlR4fx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HlR4fx"><script>var topHlR4fx = {"Desktop":{"point":"0","unit":"px"}};var bottomHlR4fx = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-iBeSY7","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-iBeSY7"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
