<?php
/**
 * Gutenverse Destination Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse Destination Section 6', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"565","Tablet":"1170"},"gap":"no","elementId":"guten-rSDInC","background":{"type":"default","color":{"r":248,"g":250,"b":255,"a":1}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"10","left":"10"}}}} -->
			<div class="section-wrapper" data-id="rSDInC"><script>var toprSDInC = {"Desktop":{"point":"0","unit":"px"}};var bottomrSDInC = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-rSDInC layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-819fld"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-819fld"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="819fld"><script>var top819fld = {"Desktop":{"point":"0","unit":"px"}};var bottom819fld = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-0tHszC","type":4,"textAlign":{"Desktop":"center"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"}},"weight":"600"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h4 class="wp-block-gutenverse-heading guten-element guten-0tHszC animated guten-element-hide desktop-fadeInUp">Subscribe To Our Newsletter</h4>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-gGV55y","alignment":{"Desktop":"center"},"textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.8"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"right":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-gGV55y animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-WQ6Ikn"} -->
			<div class="section-wrapper" data-id="WQ6Ikn"><script>var topWQ6Ikn = {"Desktop":{"point":"0","unit":"px"}};var bottomWQ6Ikn = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-WQ6Ikn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-CcDFpW","horizontalAlign":{"Desktop":"default","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-CcDFpW animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CcDFpW"><script>var topCcDFpW = {"Desktop":{"point":"0","unit":"px"}};var bottomCcDFpW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-9XYuQC","formId":{"label":"Subscribe To Our Newsletter","value":294},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[]}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-9XYuQC" data-form-id="294"><!-- wp:gutenverse/form-input-email {"elementId":"guten-COu2JB","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"399","unit":"px"},"Tablet":{"point":"461","unit":"px"},"Mobile":{"point":"160","unit":"px"}},"border":{"radius":{"Desktop":[]},"all":{"color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"inputPlaceholder":"Your Email Address ","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"20","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"placeholderColor":{"Desktop":{"r":111,"g":116,"b":126,"a":1}},"inputTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"300"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":240,"g":240,"b":240,"a":1}}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":240,"g":240,"b":240,"a":1}}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":240,"g":240,"b":240,"a":1}}},"inputBgColorNormal":{"Desktop":{"r":255,"g":255,"b":255,"a":1}}} -->
			<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-COu2JB hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email Address " name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-email -->

			<!-- wp:gutenverse/form-input-submit {"elementId":"guten-StFvik","content":"subsribe","buttonWidth":{"Desktop":""},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"30","right":"30","top":"0","left":"0"}}}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"inline"},"positioningWidth":{"Desktop":{"point":"151","unit":"px"},"Tablet":{"point":"133","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"21","bottom":"24","right":"30","left":"30"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}}} -->
			<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-StFvik"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>subsribe</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
			<!-- /wp:gutenverse/form-input-submit --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
