<?php
/**
 * Gutenverse Packages Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Packages Section 2', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-HAsR9H","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="HAsR9H"><script>var topHAsR9H = {"Desktop":{"point":"0","unit":"px"}};var bottomHAsR9H = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HAsR9H layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-XfPjU4","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-XfPjU4 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XfPjU4"><script>var topXfPjU4 = {"Desktop":{"point":"0","unit":"px"}};var bottomXfPjU4 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-2HkJ8h","imgSrc":{"media":{"imageId":73,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-palace-old-statue-1106310-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":225,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-palace-old-statue-1106310-pxhere.com-225x300.webp","orientation":"portrait"},"large":{"height":1024,"width":768,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-palace-old-statue-1106310-pxhere.com-768x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-palace-old-statue-1106310-pxhere.com.webp","height":1387,"width":1040,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"232","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-2HkJ8h"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/architecture-structure-building-palace-old-statue-1106310-pxhere.com.webp" height="1387" width="1040"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-npkGir","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="npkGir"><script>var topnpkGir = {"Desktop":{"point":"0","unit":"px"}};var bottomnpkGir = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-npkGir layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-UCQvkj","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-UCQvkj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UCQvkj"><script>var topUCQvkj = {"Desktop":{"point":"0","unit":"px"}};var bottomUCQvkj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-01HYhe","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-01HYhe">Thailand</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-enMSMx","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-enMSMx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="enMSMx"><script>var topenMSMx = {"Desktop":{"point":"0","unit":"px"}};var bottomenMSMx = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-0yzyAG","alignText":{"Desktop":"flex-end"},"text":"$450   ","focusText":"/3days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-0yzyAG"><div class="heading-section "><h2 class="heading-title">$450   <span class="heading-focus">/3days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-oH8FRj","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-oH8FRj"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vAqFGB","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="vAqFGB"><script>var topvAqFGB = {"Desktop":{"point":"0","unit":"px"}};var bottomvAqFGB = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-vAqFGB layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-Ck4vYj","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Ck4vYj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ck4vYj"><script>var topCk4vYj = {"Desktop":{"point":"0","unit":"px"}};var bottomCk4vYj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-pRfG90","title":"","starIcon":"default","rating":"5","total":"5","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="guten-element guten-star-rating guten-pRfG90"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-Y6tk64"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Y6tk64"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Y6tk64"><script>var topY6tk64 = {"Desktop":{"point":"0","unit":"px"}};var bottomY6tk64 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-BeHfq9","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-BeHfq9"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.37,"Tablet":50,"Mobile":null},"elementId":"guten-LyrnIg","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LyrnIg animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LyrnIg"><script>var topLyrnIg = {"Desktop":{"point":"0","unit":"px"}};var bottomLyrnIg = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-tk7pTN","imgSrc":{"media":{"imageId":77,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/europa-ferris-wheel-reflection-sky-landmark-night-1620789-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":169,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/europa-ferris-wheel-reflection-sky-landmark-night-1620789-pxhere.com-300x169.webp","orientation":"landscape"},"large":{"height":576,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/europa-ferris-wheel-reflection-sky-landmark-night-1620789-pxhere.com-1024x576.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/europa-ferris-wheel-reflection-sky-landmark-night-1620789-pxhere.com.webp","height":1080,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"371","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"232","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-tk7pTN"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/europa-ferris-wheel-reflection-sky-landmark-night-1620789-pxhere.com.webp" height="1080" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-mE00kN","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="mE00kN"><script>var topmE00kN = {"Desktop":{"point":"0","unit":"px"}};var bottommE00kN = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-mE00kN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-d4HFjQ","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-d4HFjQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="d4HFjQ"><script>var topd4HFjQ = {"Desktop":{"point":"0","unit":"px"}};var bottomd4HFjQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-5mXjOW","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Tablet":{"point":"20","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-5mXjOW">Singapore</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-iyykgf","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"flex-start"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-iyykgf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iyykgf"><script>var topiyykgf = {"Desktop":{"point":"0","unit":"px"}};var bottomiyykgf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-t4QW64","alignText":{"Desktop":"flex-end"},"text":"$300  ","focusText":"/2days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-t4QW64"><div class="heading-section "><h2 class="heading-title">$300  <span class="heading-focus">/2days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-EYhtFe","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50","top":"","bottom":"","left":""}}}} -->
			<div class="guten-element gutenverse-text-editor guten-EYhtFe"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-oFVx4X","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="oFVx4X"><script>var topoFVx4X = {"Desktop":{"point":"0","unit":"px"}};var bottomoFVx4X = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-oFVx4X layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-cjYR8f","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cjYR8f"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cjYR8f"><script>var topcjYR8f = {"Desktop":{"point":"0","unit":"px"}};var bottomcjYR8f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-CkRFo9","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-CkRFo9"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100},"elementId":"guten-sdpUcf"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-sdpUcf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sdpUcf"><script>var topsdpUcf = {"Desktop":{"point":"0","unit":"px"}};var bottomsdpUcf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-qYGlXH","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-qYGlXH"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":100,"Mobile":null},"elementId":"guten-wkaLEu","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"none","color":{"r":255,"g":255,"b":255,"a":1}}},"boxShadow":{"color":{"r":225,"g":225,"b":225,"a":1},"vertical":"3","blur":"15","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20","top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-wkaLEu animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wkaLEu"><script>var topwkaLEu = {"Desktop":{"point":"0","unit":"px"}};var bottomwkaLEu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-3tdgEQ","imgSrc":{"media":{"imageId":76,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/andaman-andaman-sea-krabi-Phra-Nang-thailand-beach-1637719-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":199,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/andaman-andaman-sea-krabi-Phra-Nang-thailand-beach-1637719-pxhere.com-300x199.webp","orientation":"landscape"},"large":{"height":680,"width":1024,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/andaman-andaman-sea-krabi-Phra-Nang-thailand-beach-1637719-pxhere.com-1024x680.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/andaman-andaman-sea-krabi-Phra-Nang-thailand-beach-1637719-pxhere.com.webp","height":1209,"width":1820,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"369","unit":"px"},"Tablet":{"point":"728","unit":"px"}},"height":{"Desktop":{"point":"240","unit":"px"},"Tablet":{"point":"488","unit":"px"},"Mobile":{"point":"186","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-3tdgEQ"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/andaman-andaman-sea-krabi-Phra-Nang-thailand-beach-1637719-pxhere.com.webp" height="1209" width="1820"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-XKEIS1","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="section-wrapper" data-id="XKEIS1"><script>var topXKEIS1 = {"Desktop":{"point":"0","unit":"px"}};var bottomXKEIS1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-XKEIS1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-LnPV6L","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LnPV6L"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LnPV6L"><script>var topLnPV6L = {"Desktop":{"point":"0","unit":"px"}};var bottomLnPV6L = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-aBOQR0","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-aBOQR0">Indonesia</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Tablet":null,"Mobile":50},"elementId":"guten-GxAk7Y","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Tablet":"flex-end","Mobile":"flex-start"},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-GxAk7Y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GxAk7Y"><script>var topGxAk7Y = {"Desktop":{"point":"0","unit":"px"}};var bottomGxAk7Y = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-K5AKhD","alignText":{"Desktop":"flex-end","Tablet":"flex-end","Mobile":null},"text":"$400  ","focusText":"/2days","showSub":"none","showLine":"none","lineMargin":{"Desktop":{}},"mainColor":{"r":242,"g":139,"b":56,"a":1},"mainTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"20","unit":"px"}}},"mainMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"mainPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusColor":{"r":111,"g":116,"b":126,"a":1},"focusTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"focusMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"focusPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":{},"Mobile":{},"Tablet":{}},"subPadding":{"Desktop":{},"Mobile":{},"Tablet":{}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-K5AKhD"><div class="heading-section "><h2 class="heading-title">$400  <span class="heading-focus">/2days</span></h2></div></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-SqNjee","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-SqNjee"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Gs1IPh","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"40","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="section-wrapper" data-id="Gs1IPh"><script>var topGs1IPh = {"Desktop":{"point":"0","unit":"px"}};var bottomGs1IPh = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Gs1IPh layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.29,"Tablet":null,"Mobile":100},"elementId":"guten-E4UZXL","verticalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-E4UZXL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="E4UZXL"><script>var topE4UZXL = {"Desktop":{"point":"0","unit":"px"}};var bottomE4UZXL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-248vuC","title":"","starIcon":"default","rating":"5","total":"5","margin":{"Tablet":{}},"padding":{"Tablet":{}}} -->
			<div class="guten-element guten-star-rating guten-248vuC"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":66.71,"Mobile":100,"Tablet":null},"elementId":"guten-wF08ne"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-wF08ne"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wF08ne"><script>var topwF08ne = {"Desktop":{"point":"0","unit":"px"}};var bottomwF08ne = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-UQVtAF","content":"Book Now","alignButton":{"Desktop":"center","Tablet":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-UQVtAF"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
