<?php
/**
 * Gutenverse Home Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 6', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-B5CBL9","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="B5CBL9"><script>var topB5CBL9 = {"Desktop":{"point":"0","unit":"px"}};var bottomB5CBL9 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-B5CBL9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66},"elementId":"guten-YzGHOP"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-YzGHOP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="YzGHOP"><script>var topYzGHOP = {"Desktop":{"point":"0","unit":"px"}};var bottomYzGHOP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-nUWUZP","color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"}},"weight":"600"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-nUWUZP animated guten-element-hide desktop-fadeInLeft">Travel Packages</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-Mh1v3y","color":{"r":238,"g":239,"b":243,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"96","unit":"px"},"Mobile":{"point":"52","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"96","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-11","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"-80"}},"Mobile":{"unit":"px","dimension":{"top":"-82"}}},"padding":{"Desktop":{},"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-Mh1v3y animated guten-element-hide desktop-fadeInLeft">tourS</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-UTcPyQ","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-18","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"-36","bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"40"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-text-editor guten-UTcPyQ animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null},"elementId":"guten-B8zXVl","verticalAlign":{"Desktop":"center","Tablet":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-B8zXVl"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="B8zXVl"><script>var topB8zXVl = {"Desktop":{"point":"0","unit":"px"}};var bottomB8zXVl = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-s2X9CF","content":"Discover more","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"32","bottom":"18","left":"32"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-s2X9CF"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Discover more</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
