<?php
/**
 * Gutenverse Home Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 1', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-Rthj1H","background":{"type":"default","color":{"r":248,"g":250,"b":255,"a":1}},"margin":{"Tablet":{},"Desktop":{},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"","bottom":"80"}},"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"100","left":""}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"zIndex":{"Desktop":"3"},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="Rthj1H"><script>var topRthj1H = {"Desktop":{"point":"0","unit":"px"}};var bottomRthj1H = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Rthj1H layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-XTtDqn","margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-XTtDqn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XTtDqn"><script>var topXTtDqn = {"Desktop":{"point":"0","unit":"px"}};var bottomXTtDqn = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-FppkNQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"-80"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="FppkNQ"><script>var topFppkNQ = {"Desktop":{"point":"0","unit":"px"}};var bottomFppkNQ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-FppkNQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-SXYB8n","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":112,"g":112,"b":112,"a":0.15}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SXYB8n animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SXYB8n"><script>var topSXYB8n = {"Desktop":{"point":"0","unit":"px"}};var bottomSXYB8n = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-YrqhaE","imgSrc":{"media":{"imageId":765,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/users-solid-1-150x150.webp","orientation":"landscape"},"medium":{"height":246,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/users-solid-1-300x246.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/users-solid.webp","height":548,"width":669,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"60","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-YrqhaE"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/users-solid.webp" height="548" width="669"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/heading {"elementId":"guten-WhdvNn","textAlign":{"Desktop":"center"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-WhdvNn">Private Guide</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-SHm78Y","alignment":{"Desktop":"center"},"textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-SHm78Y"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-PkFD92","content":"Learn More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"}}} -->
			<div class="guten-element guten-button-wrapper guten-PkFD92"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-TyyKR6","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":112,"g":112,"b":112,"a":0.15}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-TyyKR6 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TyyKR6"><script>var topTyyKR6 = {"Desktop":{"point":"0","unit":"px"}};var bottomTyyKR6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-8vSA1h","imgSrc":{"media":{"imageId":779,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/hand-holding-droplet-solid-1-150x150.webp","orientation":"landscape"},"medium":{"height":273,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/hand-holding-droplet-solid-1-300x273.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/hand-holding-droplet-solid.webp","height":560,"width":615,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"60","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-8vSA1h"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/hand-holding-droplet-solid.webp" height="560" width="615"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/heading {"elementId":"guten-hgRWVJ","textAlign":{"Desktop":"center"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-hgRWVJ">Affordable Price</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-WfuFyZ","alignment":{"Desktop":"center"},"textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-WfuFyZ"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-bT3eQs","content":"Learn More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"}}} -->
			<div class="guten-element guten-button-wrapper guten-bT3eQs"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-KayDAL","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":112,"g":112,"b":112,"a":0.15}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KayDAL animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KayDAL"><script>var topKayDAL = {"Desktop":{"point":"0","unit":"px"}};var bottomKayDAL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-mykR5S","imgSrc":{"media":{"imageId":778,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/headset-solid-1-150x150.webp","orientation":"landscape"},"medium":{"height":291,"width":300,"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/headset-solid-1-300x291.webp","orientation":"landscape"},"full":{"url":"' . esc_url( TRAVEY_URI ) . 'assets/img/headset-solid.webp","height":566,"width":584,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"60","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-mykR5S"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( TRAVEY_URI ) . 'assets/img/headset-solid.webp" height="566" width="584"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/heading {"elementId":"guten-SqoTNN","textAlign":{"Desktop":"center"},"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-SqoTNN">Great Support</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-UEfQqS","alignment":{"Desktop":"center"},"textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-UEfQqS"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-Uq8LST","content":"Learn More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"}}} -->
			<div class="guten-element guten-button-wrapper guten-Uq8LST"><a class="guten-button guten-button-sm" href="#"><span>Learn More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-x5xrgI","background":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","color":{"r":0,"g":21,"b":68,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"","bottom":"40","left":""}},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-x5xrgI animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="x5xrgI"><script>var topx5xrgI = {"Desktop":{"point":"0","unit":"px"}};var bottomx5xrgI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-KQoO6V","type":6,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-KQoO6V">Reservation Now</h6>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-q2BXCA","alignment":{"Desktop":"center"},"textColor":{"r":117,"g":133,"b":167,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-q2BXCA"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/heading {"elementId":"guten-48PWTX","type":6,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"spacing":{"Desktop":"0.081"},"transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"20"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-48PWTX">CALL US NOW</h6>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/button {"elementId":"guten-VUIa4d","content":"+62 361 154874","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"showIcon":true,"icon":"fas fa-phone-alt","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{}},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"}},"hoverIconColor":{"r":0,"g":21,"b":68,"a":1},"hoverTextColor":{"r":0,"g":21,"b":68,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-VUIa4d"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg fas fa-phone-alt"></i><span>+62 361 154874</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
