<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-8kbaD8","background":{"type":"default","image":{"Desktop":{"id":32,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/beach-sea-coast-water-sand-ocean-1200073-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":7,"g":7,"b":7,"a":1}},"opacity":"0.23","margin":{"Desktop":{"unit":"px","dimension":{"top":"-90","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"270","bottom":"250"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"140","bottom":"200"}}},"zIndex":{"Desktop":"1"}} -->
			<div class="section-wrapper" data-id="8kbaD8"><script>var top8kbaD8 = {"Desktop":{"point":"0","unit":"px"}};var bottom8kbaD8 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-8kbaD8 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-UyWHwF","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-UyWHwF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UyWHwF"><script>var topUyWHwF = {"Desktop":{"point":"0","unit":"px"}};var bottomUyWHwF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"textAlign":{"Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Mobile":{"point":"24","unit":"px"}},"weight":"600","font":{"label":"Lato","value":"Lato","type":"google"},"transform":"uppercase","spacing":{"Desktop":"0.075"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-1","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"-1"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-8","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide desktop-fadeInUp">welcome to travey</h1>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-oSnOnu","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Mobile":{"point":"31.2","unit":"px"}},"weight":"600","font":{"label":"Lato","value":"Lato","type":"google"},"transform":"uppercase","spacing":{"Desktop":"0.075"}},"border":{"radius":{"Tablet":{}}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-oSnOnu animated guten-element-hide desktop-fadeInUp">best way to find your dream place</h1>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-g4Ps8x","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":0.22},"typography":{"size":{"Desktop":{"point":"200","unit":"px"},"Mobile":{"point":"76","unit":"px"},"Tablet":{"point":"152","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","font":{"label":"Oswald","value":"Oswald","type":"google"},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-227","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-195"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"-102"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":""}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-g4Ps8x animated guten-element-hide desktop-fadeInUp">travey</h1>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/button {"elementId":"guten-eMzUe0","content":"Discover Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"}}} -->
			<div class="guten-element guten-button-wrapper guten-eMzUe0"><a class="guten-button animated guten-element-hide desktop-fadeInUp guten-button-sm" href="#"><span>Discover Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
