<?php
/**
 * Gutenverse About Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 3', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-YYu6qf","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"default"},"repeat":{"Desktop":"default"},"size":{"Desktop":"default"},"color":{"r":248,"g":250,"b":255,"a":1}},"backgroundOverlay":{"type":"default","color":""},"opacity":"0","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"80","top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"60"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":false}} -->
			<div class="section-wrapper" data-id="YYu6qf"><script>var topYYu6qf = {"Desktop":{"point":"0","unit":"px"}};var bottomYYu6qf = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-YYu6qf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":50},"elementId":"guten-TNhi6O","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-TNhi6O animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TNhi6O"><script>var topTNhi6O = {"Desktop":{"point":"0","unit":"px"}};var bottomTNhi6O = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-cw6lsl","icon":"gtn gtn-badge","iconColor":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"iconColorHover":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorderHover":{"radius":{"Desktop":[],"Tablet":[]}},"iconSize":{"Desktop":"48","Tablet":"48","Mobile":"40"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"prefix":"","number":"20","suffix":"+","title":"Years Of Experience","numberColor":{"Desktop":{"r":0,"g":21,"b":68,"a":1}},"titleColor":{"Desktop":{"r":111,"g":116,"b":126,"a":1}},"numberTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Tablet":{"point":"19.2","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Tablet":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none","width":"0","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-cw6lsl guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-badge"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="20" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Years Of Experience</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":50},"elementId":"guten-DMC8VU","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DMC8VU animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DMC8VU"><script>var topDMC8VU = {"Desktop":{"point":"0","unit":"px"}};var bottomDMC8VU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-uLwukU","icon":"gtn gtn-users2-light","iconColor":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"iconColorHover":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48","Tablet":"48","Mobile":"40"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"prefix":"","number":"2,450","suffix":"+","title":"Happy Customers","numberColor":{"Desktop":{"r":0,"g":21,"b":68,"a":1}},"titleColor":{"Desktop":{"r":111,"g":116,"b":126,"a":1}},"numberTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Tablet":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"0","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-uLwukU guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-users2-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="2,450" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Happy Customers</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":50},"elementId":"guten-hb53zD","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-hb53zD animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hb53zD"><script>var tophb53zD = {"Desktop":{"point":"0","unit":"px"}};var bottomhb53zD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-AF8HQn","icon":"gtn gtn-team-1-light","iconColor":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"iconColorHover":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48","Tablet":"48","Mobile":"40"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"prefix":"","number":"1,250","suffix":"+","title":"Professional Guide","numberColor":{"Desktop":{"r":0,"g":21,"b":68,"a":1}},"titleColor":{"Desktop":{"r":111,"g":116,"b":126,"a":1}},"numberTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Tablet":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"0","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-AF8HQn guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-1-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="1,250" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Professional Guide</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":50},"elementId":"guten-9b9mpL","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9b9mpL animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9b9mpL"><script>var top9b9mpL = {"Desktop":{"point":"0","unit":"px"}};var bottom9b9mpL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-VRnSde","icon":"gtn gtn-planet-earth-light","iconColor":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"iconColorHover":{"Desktop":{"r":242,"g":139,"b":56,"a":1}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"48","Tablet":"48","Mobile":"40"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"17"}},"Mobile":[]},"prefix":"","number":"250","suffix":"+","title":"Top Destinations","numberColor":{"Desktop":{"r":0,"g":21,"b":68,"a":1}},"titleColor":{"Desktop":{"r":111,"g":116,"b":126,"a":1}},"numberTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"19.2","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Tablet":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"0","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-VRnSde guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-planet-earth-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="250" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Top Destinations</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
