<?php
/**
 * Gutenverse Home Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 4', 'travey' ),
	'categories' => array( 'travey-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-HZgiTH","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="HZgiTH"><script>var topHZgiTH = {"Desktop":{"point":"0","unit":"px"}};var bottomHZgiTH = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HZgiTH layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":67.58,"Tablet":100,"Mobile":null},"elementId":"guten-MWWQtB","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-MWWQtB animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MWWQtB"><script>var topMWWQtB = {"Desktop":{"point":"0","unit":"px"}};var bottomMWWQtB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-6FasS9","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":225,"g":225,"b":225,"a":0.82}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<div class="section-wrapper" data-id="6FasS9"><script>var top6FasS9 = {"Desktop":{"point":"0","unit":"px"}};var bottom6FasS9 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6FasS9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":51.18,"Mobile":null},"elementId":"guten-XhwM1v","background":{"type":"default","image":{"Desktop":{"id":70,"image":"' . esc_url( TRAVEY_URI ) . 'assets/img/rock-building-monument-travel-landmark-tourism-1381415-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover","Mobile":"default"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-XhwM1v"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XhwM1v"><script>var topXhwM1v = {"Desktop":{"point":"0","unit":"px"}};var bottomXhwM1v = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-10HXyu","space":{"Desktop":{"point":"274","unit":"px"},"Mobile":{"point":"186","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-10HXyu"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":48.82,"Tablet":null,"Mobile":null},"elementId":"guten-t7gxgQ","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-t7gxgQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="t7gxgQ"><script>var topt7gxgQ = {"Desktop":{"point":"0","unit":"px"}};var bottomt7gxgQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-aU69Hh","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="aU69Hh"><script>var topaU69Hh = {"Desktop":{"point":"0","unit":"px"}};var bottomaU69Hh = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-aU69Hh layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38,"Mobile":50},"elementId":"guten-a8AE3k","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-a8AE3k"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a8AE3k"><script>var topa8AE3k = {"Desktop":{"point":"0","unit":"px"}};var bottoma8AE3k = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-UwGB6w","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-UwGB6w">Borobudur, Java</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62,"Mobile":50},"elementId":"guten-LUc1Ip","margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"30"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LUc1Ip"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LUc1Ip"><script>var topLUc1Ip = {"Desktop":{"point":"0","unit":"px"}};var bottomLUc1Ip = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Enx71z","type":6,"textAlign":{"Mobile":"center","Tablet":"center","Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-Enx71z">$249.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-BMgk19","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"50"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-BMgk19"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-lYQqBp","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","right":"0","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="section-wrapper" data-id="lYQqBp"><script>var toplYQqBp = {"Desktop":{"point":"0","unit":"px"}};var bottomlYQqBp = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-lYQqBp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":43,"Mobile":100,"Tablet":35.58},"elementId":"guten-Q3ABCM","verticalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Q3ABCM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Q3ABCM"><script>var topQ3ABCM = {"Desktop":{"point":"0","unit":"px"}};var bottomQ3ABCM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-szfXn3","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-szfXn3"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":57,"Mobile":100,"Tablet":null},"elementId":"guten-RjnbK6","margin":{"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RjnbK6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RjnbK6"><script>var topRjnbK6 = {"Desktop":{"point":"0","unit":"px"}};var bottomRjnbK6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-jMBFQc","content":"Book Now","buttonWidth":{"Tablet":""},"alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-jMBFQc"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":32.42,"Tablet":null},"elementId":"guten-qH3QKu","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"},"hideTablet":true,"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-qH3QKu animated guten-element-hide desktop-fadeInUp hide-tablet hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qH3QKu"><script>var topqH3QKu = {"Desktop":{"point":"0","unit":"px"}};var bottomqH3QKu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-pmOBZi","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"boxShadow":{"vertical":"3","blur":"15","position":"outline","color":{"r":225,"g":225,"b":225,"a":0.82}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"10"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="pmOBZi"><script>var toppmOBZi = {"Desktop":{"point":"0","unit":"px"}};var bottompmOBZi = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-pmOBZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-gTX3e7","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-gTX3e7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="gTX3e7"><script>var topgTX3e7 = {"Desktop":{"point":"0","unit":"px"}};var bottomgTX3e7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-xrVDuT","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40"}}}} -->
			<div class="section-wrapper" data-id="xrVDuT"><script>var topxrVDuT = {"Desktop":{"point":"0","unit":"px"}};var bottomxrVDuT = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-xrVDuT layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":54.38},"elementId":"guten-8CaVZj"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8CaVZj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8CaVZj"><script>var top8CaVZj = {"Desktop":{"point":"0","unit":"px"}};var bottom8CaVZj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-YBgxUd","type":6,"color":{"r":0,"g":21,"b":68,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-YBgxUd">Gili Meno, NTB</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45.62},"elementId":"guten-S6uUnh","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-S6uUnh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S6uUnh"><script>var topS6uUnh = {"Desktop":{"point":"0","unit":"px"}};var bottomS6uUnh = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-B99BkV","type":6,"textAlign":{"Desktop":"center"},"color":{"r":242,"g":139,"b":56,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"weight":"300"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-B99BkV">$299.00</h6>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-y8JIoR","textColor":{"r":111,"g":116,"b":126,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"point":"24","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-y8JIoR"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-SsG7v8","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"45","right":"0","left":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="SsG7v8"><script>var topSsG7v8 = {"Desktop":{"point":"0","unit":"px"}};var bottomSsG7v8 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-SsG7v8 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":43},"elementId":"guten-OktqSm","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OktqSm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OktqSm"><script>var topOktqSm = {"Desktop":{"point":"0","unit":"px"}};var bottomOktqSm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/star-rating {"elementId":"guten-6VLyrt","title":"","starIcon":"default","rating":"5","total":"5"} -->
			<div class="guten-element guten-star-rating guten-6VLyrt"><div class="rating-wrapper"><span class="rating-title"></span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
			<!-- /wp:gutenverse/star-rating --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":57},"elementId":"guten-tUmRW4"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-tUmRW4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tUmRW4"><script>var toptUmRW4 = {"Desktop":{"point":"0","unit":"px"}};var bottomtUmRW4 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-qSSpLe","content":"Book Now","alignButton":{"Desktop":"right"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":242,"g":139,"b":56,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":0,"g":21,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.075"},"lineHeight":{"Desktop":{"point":"14","unit":"px"}}}} -->
			<div class="guten-element guten-button-wrapper guten-qSSpLe"><a class="guten-button guten-button-sm" href="#"><span>Book Now</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
