<?php
/**
 * Gutenverse Home Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 6', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-i8JoSc","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"40","left":"10"}}}} -->
			<div class="section-wrapper" data-id="i8JoSc"><script>var topi8JoSc = {"Desktop":{"point":"0","unit":"px"}};var bottomi8JoSc = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-i8JoSc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-LqWuxt","margin":{"Tablet":{"unit":"px","dimension":{"left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LqWuxt animated guten-element-hide tablet-fadeInLeft mobile-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LqWuxt"><script>var topLqWuxt = {"Desktop":{"point":"0","unit":"px"}};var bottomLqWuxt = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2yD06C","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"lineHeight":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"slideInLeft"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-2yD06C animated guten-element-hide desktop-slideInLeft">Water Lava Service Menu</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-EvmBy6","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"40"}},"Tablet":{"unit":"%","dimension":{"right":"15"}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element gutenverse-text-editor guten-EvmBy6 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-TpsFS5","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}}} -->
			<div class="section-wrapper" data-id="TpsFS5"><script>var topTpsFS5 = {"Desktop":{"point":"0","unit":"px"}};var bottomTpsFS5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-TpsFS5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-AXxfxA","margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-AXxfxA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AXxfxA"><script>var topAXxfxA = {"Desktop":{"point":"0","unit":"px"}};var bottomAXxfxA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-r3rmjo","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}},"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":true,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="r3rmjo"><script>var topr3rmjo = {"Desktop":{"point":"0","unit":"px"}};var bottomr3rmjo = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-r3rmjo layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-qEyHJJ","border":{"radius":{"Desktop":{}},"bottom":{"type":"dashed","width":"1","color":{"r":0,"g":0,"b":0,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-qEyHJJ animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qEyHJJ"><script>var topqEyHJJ = {"Desktop":{"point":"0","unit":"px"}};var bottomqEyHJJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-qg8Oiv","text":"Sauna Relax","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":102,"g":71,"b":80,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":58,"g":44,"b":57,"a":1},"focusTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"focusMargin":{"Desktop":{},"Mobile":[]},"focusPadding":{"Desktop":{},"Mobile":[]},"subColor":{"r":58,"g":44,"b":57,"a":1},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.21","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} -->
			<div class="guten-element guten-advanced-heading guten-qg8Oiv"><div class="heading-section "><h2 class="heading-title">Sauna Relax<span class="heading-focus"></span></h2></div><span class="heading-subtitle">Morbi amet convallis</span></div>
			<!-- /wp:gutenverse/advanced-heading -->
			
			<!-- wp:gutenverse/advanced-heading {"elementId":"guten-LCVmqV","alignText":{"Desktop":"flex-end"},"text":"$23 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":191,"g":164,"b":152,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":102,"g":71,"b":80,"a":1},"focusTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"focusMargin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":{},"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-LCVmqV"><div class="heading-section "><h2 class="heading-title">$23 <span class="heading-focus"> / Hours</span></h2></div><span class="heading-subtitle"></span></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-vcdNVL","border":{"radius":{"Desktop":{}},"bottom":{"type":"dashed","width":"1","color":{"r":0,"g":0,"b":0,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vcdNVL animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vcdNVL"><script>var topvcdNVL = {"Desktop":{"point":"0","unit":"px"}};var bottomvcdNVL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-76nvn7","text":"Manicure","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":102,"g":71,"b":80,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":58,"g":44,"b":57,"a":1},"focusTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"focusMargin":{"Desktop":{},"Mobile":[]},"focusPadding":{"Desktop":{},"Mobile":[]},"subColor":{"r":58,"g":44,"b":57,"a":1},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.21","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} -->
			<div class="guten-element guten-advanced-heading guten-76nvn7"><div class="heading-section "><h2 class="heading-title">Manicure<span class="heading-focus"></span></h2></div><span class="heading-subtitle">Morbi amet convallis</span></div>
			<!-- /wp:gutenverse/advanced-heading -->
			
			<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Y4P7Wt","alignText":{"Desktop":"flex-end"},"text":"$14 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":191,"g":164,"b":152,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":102,"g":71,"b":80,"a":1},"focusTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-Y4P7Wt"><div class="heading-section "><h2 class="heading-title">$14 <span class="heading-focus"> / Hours</span></h2></div><span class="heading-subtitle"></span></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-HEQPam","border":{"radius":{"Desktop":{}},"bottom":{"type":"dashed","width":"1","color":{"r":0,"g":0,"b":0,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HEQPam animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HEQPam"><script>var topHEQPam = {"Desktop":{"point":"0","unit":"px"}};var bottomHEQPam = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-ovdlW5","text":"Pedicure","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":102,"g":71,"b":80,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":58,"g":44,"b":57,"a":1},"focusTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"focusMargin":{"Desktop":{},"Mobile":[]},"focusPadding":{"Desktop":{},"Mobile":[]},"subColor":{"r":58,"g":44,"b":57,"a":1},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.21","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} -->
			<div class="guten-element guten-advanced-heading guten-ovdlW5"><div class="heading-section "><h2 class="heading-title">Pedicure<span class="heading-focus"></span></h2></div><span class="heading-subtitle">Morbi amet convallis</span></div>
			<!-- /wp:gutenverse/advanced-heading -->
			
			<!-- wp:gutenverse/advanced-heading {"elementId":"guten-2Qi20g","alignText":{"Desktop":"flex-end"},"text":"$16 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":191,"g":164,"b":152,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":102,"g":71,"b":80,"a":1},"focusTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-2Qi20g"><div class="heading-section "><h2 class="heading-title">$16 <span class="heading-focus"> / Hours</span></h2></div><span class="heading-subtitle"></span></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-8c2CiF","border":{"radius":{"Desktop":{}},"bottom":{"type":"dashed","width":"1","color":{"r":0,"g":0,"b":0,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8c2CiF animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8c2CiF"><script>var top8c2CiF = {"Desktop":{"point":"0","unit":"px"}};var bottom8c2CiF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-dnlsqW","text":"Body Wraps","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":102,"g":71,"b":80,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":58,"g":44,"b":57,"a":1},"focusTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"focusMargin":{"Desktop":{},"Mobile":[]},"focusPadding":{"Desktop":{},"Mobile":[]},"subColor":{"r":58,"g":44,"b":57,"a":1},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.21","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} -->
			<div class="guten-element guten-advanced-heading guten-dnlsqW"><div class="heading-section "><h2 class="heading-title">Body Wraps<span class="heading-focus"></span></h2></div><span class="heading-subtitle">Morbi amet convallis</span></div>
			<!-- /wp:gutenverse/advanced-heading -->
			
			<!-- wp:gutenverse/advanced-heading {"elementId":"guten-S9tisC","alignText":{"Desktop":"flex-end"},"text":"$31 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"r":191,"g":164,"b":152,"a":1},"mainTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"r":102,"g":71,"b":80,"a":1},"focusTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
			<div class="guten-element guten-advanced-heading guten-S9tisC"><div class="heading-section "><h2 class="heading-title">$31 <span class="heading-focus"> / Hours</span></h2></div><span class="heading-subtitle"></span></div>
			<!-- /wp:gutenverse/advanced-heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-nwHUB1","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"default"},"repeat":{"Desktop":"default"},"size":{"Desktop":"default"},"color":{"r":255,"g":252,"b":249,"a":1}},"opacity":"0.5","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"0","bottom":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nwHUB1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nwHUB1"><script>var topnwHUB1 = {"Desktop":{"point":"0","unit":"px"}};var bottomnwHUB1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-G21plg","verticalAlign":"center","background":{"type":"default","image":{"Desktop":{"id":155,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/tree-nature-branch-blossom-snow-winter-635980-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.5","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"70","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"800"}} -->
			<div class="section-wrapper" data-id="G21plg"><script>var topG21plg = {"Desktop":{"point":"0","unit":"px"}};var bottomG21plg = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-G21plg animated guten-element-hide desktop-fadeIn layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-8u51Ki","background":{"type":"default","color":{"r":191,"g":164,"b":152,"a":0.71}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"100","left":"100"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeIn","Mobile":"fadeIn"},"duration":"normal","delay":"900"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8u51Ki animated guten-element-hide desktop-fadeIn tablet-fadeIn mobile-fadeIn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8u51Ki"><script>var top8u51Ki = {"Desktop":{"point":"0","unit":"px"}};var bottom8u51Ki = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-9p11dV","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"500"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningAlign":{"Tablet":"center"},"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-9p11dV">Get Up To</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-mPNOAn","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"lineHeight":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"600"},"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-mPNOAn">25%</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-iqWVSH","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}}},"margin":{"Mobile":[]},"padding":{"Mobile":[]},"positioningType":{"Desktop":"default"},"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-iqWVSH">Discount</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
