<?php
/**
 * Gutenverse Contact Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-zQgZ3t","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"80","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"50"}}}} -->
			<div class="section-wrapper" data-id="zQgZ3t"><script>var topzQgZ3t = {"Desktop":{"point":"0","unit":"px"}};var bottomzQgZ3t = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-zQgZ3t layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-9aGyS1","margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9aGyS1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9aGyS1"><script>var top9aGyS1 = {"Desktop":{"point":"0","unit":"px"}};var bottom9aGyS1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Pp6VLb","imgSrc":{"media":{"imageId":53,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-1024x1024.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp","height":1920,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"124","unit":"px"},"Tablet":{"point":"146","unit":"px"},"Mobile":{"point":"73","unit":"px"}},"height":{"Tablet":{"point":"145","unit":"px"},"Mobile":{"point":"72","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Pp6VLb animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp" height="1920" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-nuAQtp","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"},"Tablet":{"point":"46","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-nuAQtp animated guten-element-hide desktop-fadeInUp">Spa Branch</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-gUmaFf","textAlign":{"Desktop":"center"},"color":{"r":251,"g":250,"b":250,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.125"}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-12","right":"0","left":"","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"top":"-17"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"hideMobile":true,"positioningType":{"Desktop":"default","Tablet":"default"},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"-19","unit":"px"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Tablet":{"unit":"%","point":""}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-gUmaFf hide-mobile">WaterLava</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-rbVW8W","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"%","dimension":{"bottom":"","top":"-3","right":"","left":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"6","left":"6","top":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element gutenverse-text-editor guten-rbVW8W animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-m0gZfz","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="m0gZfz"><script>var topm0gZfz = {"Desktop":{"point":"0","unit":"px"}};var bottomm0gZfz = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-m0gZfz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-FUWsD2","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"50","left":"50"}},"Mobile":{"unit":"px","dimension":{"right":"50","left":"50","bottom":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-FUWsD2 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FUWsD2"><script>var topFUWsD2 = {"Desktop":{"point":"0","unit":"px"}};var bottomFUWsD2 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SXpcpm","type":3,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-SXpcpm">Bali</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-cQ3LGO","alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"19.5","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-cQ3LGO"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Legian Kuta ST-19 Suite 221 Denpasar, Bali</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-7lgHt3","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"50","left":"50"}},"Mobile":{"unit":"px","dimension":{"right":"50","left":"50"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7lgHt3 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7lgHt3"><script>var top7lgHt3 = {"Desktop":{"point":"0","unit":"px"}};var bottom7lgHt3 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-UtGmmP","type":3,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-UtGmmP">Surabaya</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-2GASis","alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"19.5","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Mobile":{}},"padding":{"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-2GASis"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sudirman SB-23 Suite 421, Wonokromo, Surabaya</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-9dIkUy","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"50","left":"50"}},"Mobile":{"unit":"px","dimension":{"right":"50","left":"50"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9dIkUy animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9dIkUy"><script>var top9dIkUy = {"Desktop":{"point":"0","unit":"px"}};var bottom9dIkUy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Um1iTd","type":3,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-Um1iTd">Jakarta</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-QEa965","alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"19.5","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-QEa965"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Cempaka Putih JT-54 Suite 191 Cipayung, Jaksel</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-k8yi3f","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"50","left":"50"}},"Mobile":{"unit":"px","dimension":{"right":"50","left":"50"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-k8yi3f animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="k8yi3f"><script>var topk8yi3f = {"Desktop":{"point":"0","unit":"px"}};var bottomk8yi3f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-NOf42m","type":3,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-NOf42m">Yogyakarta</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-vEuUUc","alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"19.5","unit":"px"},"Mobile":{"point":"18","unit":"px"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-vEuUUc"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Diponegoro YT-19 Suite 311 Bantul, Yogyakarta</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
