<?php
/**
 * Gutenverse Home Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 2', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"100","left":"10","right":"10","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="5e9nnt"><script>var top5e9nnt = {"Desktop":{"point":"0","unit":"px"}};var bottom5e9nnt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-dgrmOB","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":161,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_XVEZDYZASS.webp"},"Mobile":{"id":161,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_XVEZDYZASS.webp"}},"position":{"Desktop":"top center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(244, 245, 245, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(12, 12, 12, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"0"}},"Desktop":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight"},"duration":"normal","delay":"100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dgrmOB animated guten-element-hide desktop-fadeInDown tablet-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dgrmOB"><script>var topdgrmOB = {"Desktop":{"point":"0","unit":"px"}};var bottomdgrmOB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-YS4OxF","space":{"Desktop":{"point":"273","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-YS4OxF"></div>
			<!-- /wp:gutenverse/spacer -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-xRUlJL","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-xRUlJL">MASSAGES</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-yBrJl6","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":162,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_ZTASYNHMPV.webp"},"Mobile":{"id":162,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_ZTASYNHMPV.webp"}},"position":{"Desktop":"center left","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(248, 248, 248, 0)","opacity":0,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(21, 21, 21, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Tablet":{},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-yBrJl6 animated guten-element-hide desktop-fadeInUp tablet-slideInUp mobile-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yBrJl6"><script>var topyBrJl6 = {"Desktop":{"point":"0","unit":"px"}};var bottomyBrJl6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-XuSqUc","space":{"Desktop":{"point":"273","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-XuSqUc"></div>
			<!-- /wp:gutenverse/spacer -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-SIuecP","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-SIuecP">THERAPIES</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-isqlVu","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":163,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_NTQWZSB6SC.webp"},"Mobile":{"id":163,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_NTQWZSB6SC.webp"}},"position":{"Desktop":"center left","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","opacity":0,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(12, 12, 12, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-isqlVu animated guten-element-hide desktop-fadeInDown tablet-fadeInRight mobile-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="isqlVu"><script>var topisqlVu = {"Desktop":{"point":"0","unit":"px"}};var bottomisqlVu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-LuUZiP","space":{"Desktop":{"point":"273","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-LuUZiP"></div>
			<!-- /wp:gutenverse/spacer -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-JP0sjR","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-JP0sjR">RELAXATION</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
