<?php
/**
 * Gutenverse Home Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-uvZMpK","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"bottomDivider":{"type":"waves","width":{"Desktop":"140","Mobile":"169"},"height":{"Desktop":"90","Tablet":"65","Mobile":"47"},"colorMode":"default","color":{"r":254,"g":254,"b":254,"a":1},"front":true,"flip":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"180"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"80"}}}} -->
			<div class="section-wrapper" data-id="uvZMpK"><script>var topuvZMpK = {"Desktop":{"point":"0","unit":"px"}};var bottomuvZMpK = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-uvZMpK layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom guten-shape-zindex"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-VcgnLu"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-VcgnLu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VcgnLu"><script>var topVcgnLu = {"Desktop":{"point":"0","unit":"px"}};var bottomVcgnLu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-GgkpPT","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
			<div class="section-wrapper" data-id="GgkpPT"><script>var topGgkpPT = {"Desktop":{"point":"0","unit":"px"}};var bottomGgkpPT = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-GgkpPT layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-HJA46S"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HJA46S"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HJA46S"><script>var topHJA46S = {"Desktop":{"point":"0","unit":"px"}};var bottomHJA46S = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-fIZCZL","imgSrc":{"media":{"imageId":53,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-1024x1024.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp","height":1920,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"124","unit":"px"},"Mobile":{"point":"73","unit":"px"}},"height":{"Mobile":{"point":"72","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"align":{"Desktop":"center"},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-fIZCZL animated guten-element-hide desktop-fadeInDown"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp" height="1920" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-uHZDbV","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"},"Tablet":{"point":"46","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-uHZDbV animated guten-element-hide desktop-fadeInDown tablet-fadeInRight mobile-fadeInRight">An Incredible Spa Experience</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-tTxbfm","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-tTxbfm animated guten-element-hide desktop-fadeInDown tablet-fadeInDown mobile-fadeInDown"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisl. Etiam efficitur in arcut lacinia. Donec scelerisque enim non dictum aliquet. Sed ecnunc suspendisse volutpat elit nec nisi congue tristique eu at velit.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-hfZCos","textAlign":{"Desktop":"center"},"color":{"r":250,"g":246,"b":243,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"100","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.125"},"lineHeight":{"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"100","unit":"px"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-19","right":"0","left":"","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-157"}},"Mobile":{"unit":"%","dimension":{"top":"-95","right":"","bottom":"","left":""}}},"padding":{"Desktop":{},"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningWidth":{"Tablet":{"unit":"%","point":"100"}},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Tablet":{"unit":"%","point":""}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-hfZCos">WaterLava</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/image {"elementId":"guten-8Zz91Y","imgSrc":{"media":{"imageId":88,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-150x150.webp","orientation":"landscape"},"medium":{"height":71,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-300x71.webp","orientation":"landscape"},"large":{"height":244,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-1024x244.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp","height":457,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"280","unit":"px"},"Mobile":{"point":"174","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":[],"Tablet":[]}},"align":{"Desktop":"center"},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":"10"}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-8Zz91Y animated guten-element-hide desktop-fadeInDown tablet-fadeInLeft mobile-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp" height="457" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-SWsBfI","type":5,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"400"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-SWsBfI animated guten-element-hide desktop-fadeInDown">WaterLava Owner</h5>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
