<?php
/**
 * Gutenverse Home Section 5 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 5', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-BrKL3j","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-7","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","left":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="BrKL3j"><script>var topBrKL3j = {"Desktop":{"point":"0","unit":"px"}};var bottomBrKL3j = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-BrKL3j layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":100},"elementId":"guten-Bm66rW","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Bm66rW animated guten-element-hide desktop-fadeIn tablet-fadeInLeft mobile-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Bm66rW"><script>var topBm66rW = {"Desktop":{"point":"0","unit":"px"}};var bottomBm66rW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-MjrZ5t","profileType":"overlay","overlayType":"default","src":{"id":534,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/nature-sweet-flower-honey-pollen-yellow-1377266-pxhere.com.webp"},"name":"Nutritionist","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"45","unit":"px"}}},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"}}},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgWidth":{"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-MjrZ5t"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/nature-sweet-flower-honey-pollen-yellow-1377266-pxhere.com.webp" alt="Nutritionist"/><div class="profile-body undefined"><h3 class="profile-title ">Nutritionist</h3><p class="profile-sub">Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.</p></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":100},"elementId":"guten-FlD3hM","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-FlD3hM animated guten-element-hide desktop-fadeIn tablet-fadeInUp mobile-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FlD3hM"><script>var topFlD3hM = {"Desktop":{"point":"0","unit":"px"}};var bottomFlD3hM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-MbeVaO","profileType":"overlay","src":{"id":153,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-plant-woman-flower-petal-feet-1166839-pxhere.com.webp"},"name":"Pedicure","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"45","unit":"px"}}},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"}}},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgWidth":{"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-MbeVaO"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-plant-woman-flower-petal-feet-1166839-pxhere.com.webp" alt="Pedicure"/><div class="profile-body undefined"><h3 class="profile-title ">Pedicure</h3><p class="profile-sub">Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.</p></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":100},"elementId":"guten-WuTsHg","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-WuTsHg animated guten-element-hide desktop-fadeIn tablet-fadeInRight mobile-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WuTsHg"><script>var topWuTsHg = {"Desktop":{"point":"0","unit":"px"}};var bottomWuTsHg = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-B1hc3x","profileType":"overlay","src":{"id":167,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/people-meal-child-baking-ceremony-infant-982394-pxhere.com.webp"},"name":"Waterlava stone","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"45","unit":"px"}}},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"}}},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"margin":{"Tablet":{"unit":"px","dimension":{"top":"-10","bottom":"-10"}}},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"imgRotate":{"Mobile":""},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"nameSpace":{"Desktop":""}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-B1hc3x"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/people-meal-child-baking-ceremony-infant-982394-pxhere.com.webp" alt="Waterlava stone"/><div class="profile-body undefined"><h3 class="profile-title ">Waterlava stone</h3><p class="profile-sub">Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.</p></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
