<?php
/**
 * Gutenverse About Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 3', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-KJrouN","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"bottomDivider":{"type":"waves","height":{"Desktop":"82","Mobile":"65","Tablet":"54"},"width":{"Desktop":"113","Mobile":"142","Tablet":""},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-15","left":"0"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"100","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"100","left":"10"}}}} -->
			<div class="section-wrapper" data-id="KJrouN"><script>var topKJrouN = {"Desktop":{"point":"0","unit":"px"}};var bottomKJrouN = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-KJrouN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-Hf10ZC","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{}},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Hf10ZC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Hf10ZC"><script>var topHf10ZC = {"Desktop":{"point":"0","unit":"px"}};var bottomHf10ZC = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-0JHOFq","margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}}} -->
			<div class="section-wrapper" data-id="0JHOFq"><script>var top0JHOFq = {"Desktop":{"point":"0","unit":"px"}};var bottom0JHOFq = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-0JHOFq layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-VsfLBs"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-VsfLBs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VsfLBs"><script>var topVsfLBs = {"Desktop":{"point":"0","unit":"px"}};var bottomVsfLBs = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-rTqxBE","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="rTqxBE"><script>var toprTqxBE = {"Desktop":{"point":"0","unit":"px"}};var bottomrTqxBE = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-rTqxBE layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-lsnEpU","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lsnEpU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lsnEpU"><script>var toplsnEpU = {"Desktop":{"point":"0","unit":"px"}};var bottomlsnEpU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-3RwcVU","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"},"Tablet":{"point":"46","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-3RwcVU animated guten-element-hide desktop-fadeInUp">Why Choose Us</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-wVcMij","textAlign":{"Desktop":"center"},"color":{"r":250,"g":246,"b":243,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.125"},"lineHeight":{"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-15","right":"","left":"","bottom":""}},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"17"},"Tablet":{"unit":"%","point":"0"},"Mobile":{"point":"0","unit":"px"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":"0"},"Mobile":{"point":"0","unit":"px"}},"positioningTop":{"Desktop":{"unit":"%","point":"-22"},"Mobile":{"point":"-10","unit":"px"},"Tablet":{"unit":"%","point":"-22"}},"positioningBottom":{"Tablet":{"unit":"%","point":"0"},"Mobile":{"point":"0","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-wVcMij">Why Us</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-D4rCAh","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","left":"25"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"2","left":"10"}},"Mobile":{"unit":"%","dimension":{"right":"6","left":"6"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-D4rCAh animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-MTNIb5","margin":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}}} -->
			<div class="section-wrapper" data-id="MTNIb5"><script>var topMTNIb5 = {"Desktop":{"point":"0","unit":"px"}};var bottomMTNIb5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-MTNIb5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-dOKAFZ","background":{"type":"default","image":{"Desktop":{"id":171,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_NAQDACNUFE.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.6","verticalAlign":{"Desktop":"default"},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"75","bottom":"10","right":"10","left":"10"}},"Tablet":{"unit":"%","dimension":{"top":"70"}},"Mobile":{"unit":"%","dimension":{"top":"75","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dOKAFZ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dOKAFZ"><script>var topdOKAFZ = {"Desktop":{"point":"0","unit":"px"}};var bottomdOKAFZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-sZAwR4","type":3,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Mobile":{},"Desktop":{}},"padding":{"Mobile":{},"Desktop":{"unit":"px","dimension":{"top":"40"}}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-sZAwR4">Easy For Book</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-kGuzO1","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-kGuzO1"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcor odio vitae eleifend.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-U2mnyu","content":"View Detail","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":58,"g":44,"b":57,"a":0}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":225,"g":214,"b":203,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-U2mnyu"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-il0IKv","background":{"type":"default","image":{"Desktop":{"id":140,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"center left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"75","bottom":"10","right":"10","left":"10"}},"Tablet":{"unit":"%","dimension":{"top":"60","right":"","bottom":"","left":""}},"Mobile":{"unit":"%","dimension":{"top":"75","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-il0IKv animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="il0IKv"><script>var topil0IKv = {"Desktop":{"point":"0","unit":"px"}};var bottomil0IKv = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2t4DcJ","type":3,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-2t4DcJ">Gift Packages</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-ZcMvoE","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","left":"0","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-ZcMvoE"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcor odio vitae eleifend.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-iPfhCR","content":"View Detail","paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"buttonBackground":{"type":"default","color":{"r":58,"g":44,"b":57,"a":0}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":225,"g":214,"b":203,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-iPfhCR"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-O3QGIs","margin":{"Tablet":{}},"padding":{"Tablet":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-O3QGIs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="O3QGIs"><script>var topO3QGIs = {"Desktop":{"point":"0","unit":"px"}};var bottomO3QGIs = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-dWEPV6","margin":{"Tablet":{}},"padding":{"Tablet":{}},"wrapColumn":{"Desktop":true,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="dWEPV6"><script>var topdWEPV6 = {"Desktop":{"point":"0","unit":"px"}};var bottomdWEPV6 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-dWEPV6 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-SlMdLU","background":{"type":"default","image":{"Desktop":{"id":134,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/flower-food-relax-produce-rest-baking-914313-pxhere.com.webp"}},"position":{"Desktop":"top center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundHover":{"type":"default"},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.6","verticalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"10"}},"Mobile":{},"Tablet":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"8","bottom":"8","right":"0","left":"6"}},"Mobile":{"unit":"%","dimension":{"left":"10","top":"10","right":"10","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"40"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SlMdLU animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SlMdLU"><script>var topSlMdLU = {"Desktop":{"point":"0","unit":"px"}};var bottomSlMdLU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XGgPrG","type":3,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"%","dimension":{"right":"38","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-XGgPrG">Natural Aroma Massage</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-AQz7Td","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"%","dimension":{"right":"38"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-AQz7Td"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcor odio vitae eleifend.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-eMp4Ru","content":"View Detail","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{}},"buttonBackground":{"type":"default","color":{"r":58,"g":44,"b":57,"a":0}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":225,"g":214,"b":203,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-eMp4Ru"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-73nYTI","background":{"type":"default","image":{"Desktop":{"id":157,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-floor-furniture-room-relaxation-bed-894972-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"10"}},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"8","bottom":"8","right":"0","left":"6"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"40"}},"Mobile":{"unit":"%","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-73nYTI animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="73nYTI"><script>var top73nYTI = {"Desktop":{"point":"0","unit":"px"}};var bottom73nYTI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Z7ZBI0","type":3,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"%","dimension":{"right":"38","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}}} -->
			<h3 class="wp-block-gutenverse-heading guten-element guten-Z7ZBI0">Essential Salon &amp; Spa</h3>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-O3CNDj","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"%","dimension":{"right":"38"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-O3CNDj"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcor odio vitae eleifend.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-fBzCML","content":"View Detail","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":58,"g":44,"b":57,"a":0}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":225,"g":214,"b":203,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":225,"g":214,"b":203,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-fBzCML"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
