<?php
/**
 * Gutenverse Home Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 3', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-CoqbuA","background":{"type":"default","color":""},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="CoqbuA"><script>var topCoqbuA = {"Desktop":{"point":"0","unit":"px"}};var bottomCoqbuA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-CoqbuA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-dl8OBm","background":{"type":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dl8OBm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dl8OBm"><script>var topdl8OBm = {"Desktop":{"point":"0","unit":"px"}};var bottomdl8OBm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-k4jsJY","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
			<div class="section-wrapper" data-id="k4jsJY"><script>var topk4jsJY = {"Desktop":{"point":"0","unit":"px"}};var bottomk4jsJY = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-k4jsJY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-bKnrrp","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bKnrrp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bKnrrp"><script>var topbKnrrp = {"Desktop":{"point":"0","unit":"px"}};var bottombKnrrp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7GFvGV","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"40"}}}} -->
			<div class="section-wrapper" data-id="7GFvGV"><script>var top7GFvGV = {"Desktop":{"point":"0","unit":"px"}};var bottom7GFvGV = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-7GFvGV layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-o9lZgK","margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-o9lZgK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="o9lZgK"><script>var topo9lZgK = {"Desktop":{"point":"0","unit":"px"}};var bottomo9lZgK = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-aZNCj5","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="aZNCj5"><script>var topaZNCj5 = {"Desktop":{"point":"0","unit":"px"}};var bottomaZNCj5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-aZNCj5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-7pLije","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7pLije"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7pLije"><script>var top7pLije = {"Desktop":{"point":"0","unit":"px"}};var bottom7pLije = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-lICvzB","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInRight"},"duration":"normal","delay":""}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-lICvzB animated guten-element-hide desktop-fadeInUp tablet-fadeInDown mobile-fadeInRight">Best Service For You</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-e0HmOv","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"10","left":"10"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"delay":"100","duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-e0HmOv animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-9yyP9k","textAlign":{"Desktop":"center"},"color":{"r":251,"g":250,"b":250,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0","Tablet":"0"},"lineHeight":{"Mobile":{"point":"70","unit":"px"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-17","right":"","left":"","bottom":""}},"Mobile":{"unit":"%","dimension":{"top":"-158","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":"-35"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningAlign":{"Desktop":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"}},"positioningBottom":{"Mobile":{"unit":"%","point":""}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-9yyP9k">S e r v i c e s</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-F92P6u","margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="F92P6u"><script>var topF92P6u = {"Desktop":{"point":"0","unit":"px"}};var bottomF92P6u = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-F92P6u layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-zpow0W","horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInDown"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zpow0W animated guten-element-hide desktop-fadeInUp tablet-slideInUp mobile-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zpow0W"><script>var topzpow0W = {"Desktop":{"point":"0","unit":"px"}};var bottomzpow0W = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-LfB6C3","imgSrc":{"media":{"imageId":223,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid-150x150.webp","orientation":"landscape"},"medium":{"height":267,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid-300x267.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid.webp","height":512,"width":576,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"height":{"Desktop":{"point":"50","unit":"px"},"Mobile":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-LfB6C3"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid.webp" height="512" width="576"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-eDt7lm","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
			<div class="guten-element guten-icon-list guten-eDt7lm"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-MZQcYr","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-MZQcYr"><a id="guten-MZQcYr"><span class="list-text no-icon">Rescue Treatment</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-OHqBih","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OHqBih animated guten-element-hide desktop-fadeInDown tablet-fadeInUp mobile-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OHqBih"><script>var topOHqBih = {"Desktop":{"point":"0","unit":"px"}};var bottomOHqBih = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-huyC6r","imgSrc":{"media":{"imageId":224,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":188,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid-188x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid.webp","height":512,"width":320,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"35","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-huyC6r"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid.webp" height="512" width="320"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-k1nffZ","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Mobile":[]}} -->
			<div class="guten-element guten-icon-list guten-k1nffZ"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-G11rm6","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-G11rm6"><a id="guten-G11rm6"><span class="list-text no-icon">Scalp Massage</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-P8by1D","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInDown"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-P8by1D animated guten-element-hide desktop-fadeInUp tablet-slideInUp mobile-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="P8by1D"><script>var topP8by1D = {"Desktop":{"point":"0","unit":"px"}};var bottomP8by1D = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-YpSkG5","imgSrc":{"media":{"imageId":225,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":225,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid-225x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid.webp","height":512,"width":384,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-YpSkG5"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid.webp" height="512" width="384"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-qqZt8X","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}}} -->
			<div class="guten-element guten-icon-list guten-qqZt8X"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-jVTAu9","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-jVTAu9"><a id="guten-jVTAu9"><span class="list-text no-icon">Body Scrub</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-y9oviT","animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-y9oviT animated guten-element-hide desktop-fadeInDown tablet-fadeInDown mobile-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="y9oviT"><script>var topy9oviT = {"Desktop":{"point":"0","unit":"px"}};var bottomy9oviT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-dPBzc9","imgSrc":{"media":{"imageId":226,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid.webp","height":512,"width":512,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-dPBzc9"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid.webp" height="512" width="512"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-gAuerZ","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
			<div class="guten-element guten-icon-list guten-gAuerZ"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-3ILi2x","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-3ILi2x"><a id="guten-3ILi2x"><span class="list-text no-icon">Natural Mask</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-VoARKT","animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-VoARKT animated guten-element-hide desktop-fadeInUp tablet-fadeInDown mobile-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VoARKT"><script>var topVoARKT = {"Desktop":{"point":"0","unit":"px"}};var bottomVoARKT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-DJ9ONM","imgSrc":{"media":{"imageId":227,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid-150x150.webp","orientation":"landscape"},"medium":{"height":240,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid-300x240.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid.webp","height":512,"width":640,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-DJ9ONM"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid.webp" height="512" width="640"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-HyQpjD","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
			<div class="guten-element guten-icon-list guten-HyQpjD"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-SQt1zN","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-SQt1zN"><a id="guten-SQt1zN"><span class="list-text no-icon">Pranama Stone</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33},"elementId":"guten-zH2ogS","margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zH2ogS animated guten-element-hide desktop-fadeInDown tablet-fadeInDown mobile-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zH2ogS"><script>var topzH2ogS = {"Desktop":{"point":"0","unit":"px"}};var bottomzH2ogS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Ho0zck","imgSrc":{"media":{"imageId":228,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":267,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid-300x267.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid.webp","height":512,"width":576,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Ho0zck"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid.webp" height="512" width="576"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-CY624m","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}}} -->
			<div class="guten-element guten-icon-list guten-CY624m"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-KicTLu","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-KicTLu"><a id="guten-KicTLu"><span class="list-text no-icon">Swan Spa</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
