<?php
/**
 * Gutenverse About Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 2', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-4JxZQk","background":{"type":"default","image":{"Desktop":{"id":367,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_SJX0UPY4VO.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.6","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"-10"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":"100"}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="4JxZQk"><script>var top4JxZQk = {"Desktop":{"point":"0","unit":"px"}};var bottom4JxZQk = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4JxZQk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-zNideS","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zNideS animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zNideS"><script>var topzNideS = {"Desktop":{"point":"0","unit":"px"}};var bottomzNideS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-cw6lsl","icon":"gtn gtn-diploma-light","iconColor":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorder":{"radius":{"Desktop":{}}},"iconColorHover":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorderHover":{"radius":{"Desktop":{},"Tablet":{}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"prefix":"","number":"23","suffix":"+","title":"EXPERIENCE","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"14.4","unit":"px"}}},"numberBottomSpace":{"Desktop":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":129,"g":121,"b":126,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{}}} -->
			<div class="guten-element guten-cw6lsl guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-diploma-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="23" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">EXPERIENCE</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-DMC8VU","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DMC8VU animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DMC8VU"><script>var topDMC8VU = {"Desktop":{"point":"0","unit":"px"}};var bottomDMC8VU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-uLwukU","icon":"gtn gtn-review-light","iconColor":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconColorHover":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorderHover":{"radius":{"Desktop":{}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"prefix":"","number":"150","suffix":"+","title":"CUSTOMERS","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"14.4","unit":"px"}}},"numberBottomSpace":{"Desktop":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":129,"g":121,"b":126,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}} -->
			<div class="guten-element guten-uLwukU guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-review-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="150" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">CUSTOMERS</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-hb53zD","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-hb53zD animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hb53zD"><script>var tophb53zD = {"Desktop":{"point":"0","unit":"px"}};var bottomhb53zD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-AF8HQn","icon":"gtn gtn-Massage-table-light","iconColor":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorder":{"radius":{"Desktop":{}}},"iconColorHover":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorderHover":{"radius":{"Desktop":{}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"150","suffix":"+","title":"TREATMENTS","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"14.4","unit":"px"}}},"numberBottomSpace":{"Desktop":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":129,"g":121,"b":126,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}} -->
			<div class="guten-element guten-AF8HQn guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-Massage-table-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="150" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">TREATMENTS</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-9b9mpL","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9b9mpL animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9b9mpL"><script>var top9b9mpL = {"Desktop":{"point":"0","unit":"px"}};var bottom9b9mpL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-VRnSde","icon":"gtn gtn-hot-stone-light","iconColor":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorder":{"radius":{"Desktop":{}}},"iconColorHover":{"Desktop":{"r":225,"g":214,"b":203,"a":1}},"iconBorderHover":{"radius":{"Desktop":{}}},"iconSize":{"Desktop":"48"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"150","suffix":"+","title":"SPECIALIST","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"}},"weight":"600"},"titleTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"14.4","unit":"px"}}},"numberBottomSpace":{"Desktop":"10"},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":129,"g":121,"b":126,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}} -->
			<div class="guten-element guten-VRnSde guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-hot-stone-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="150" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">SPECIALIST</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
