<?php
/**
 * Gutenverse Contact Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Section 2', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-nBNnz2","background":{"type":"default","image":{"Desktop":{"id":140,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"bottom right","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="nBNnz2"><script>var topnBNnz2 = {"Desktop":{"point":"0","unit":"px"}};var bottomnBNnz2 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-nBNnz2 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-OTlYGA","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OTlYGA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OTlYGA"><script>var topOTlYGA = {"Desktop":{"point":"0","unit":"px"}};var bottomOTlYGA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-66qPxM","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"},"Tablet":{"point":"46","unit":"px"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"decoration":"default","style":"default"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"positioningType":{"Tablet":"default"},"positioningLocation":"default"} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-66qPxM animated guten-element-hide desktop-fadeInUp">Interested In Joining Let\'s Contact Us</h1>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","alignment":{"Desktop":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"20"}},"Mobile":[],"Tablet":{}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","top":"0","bottom":"0","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-kxbE7L animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-NQtTOX","content":"contact us","buttonWidth":{"Desktop":"24","Tablet":"33","Mobile":"58"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"25","bottom":"25"}}},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","color":{"r":225,"g":214,"b":203,"a":1}}},"border":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}}} -->
			<div class="guten-element guten-button-wrapper guten-NQtTOX"><a class="guten-button animated guten-element-hide desktop-fadeInUp guten-button-sm" href="#"><span>contact us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
