<?php
/**
 * Gutenverse Services Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Services Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-OBBLdp","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}}}} -->
			<div class="section-wrapper" data-id="OBBLdp"><script>var topOBBLdp = {"Desktop":{"point":"0","unit":"px"}};var bottomOBBLdp = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-OBBLdp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-MF5wtV","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"50","top":"0","right":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-MF5wtV"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MF5wtV"><script>var topMF5wtV = {"Desktop":{"point":"0","unit":"px"}};var bottomMF5wtV = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-CoqbuA","background":{"type":"default","color":""},"margin":{"Tablet":[],"Desktop":{}},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Desktop":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="CoqbuA"><script>var topCoqbuA = {"Desktop":{"point":"0","unit":"px"}};var bottomCoqbuA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-CoqbuA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-dl8OBm","background":{"type":"default"},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dl8OBm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dl8OBm"><script>var topdl8OBm = {"Desktop":{"point":"0","unit":"px"}};var bottomdl8OBm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-k4jsJY","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="k4jsJY"><script>var topk4jsJY = {"Desktop":{"point":"0","unit":"px"}};var bottomk4jsJY = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-k4jsJY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-bKnrrp","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bKnrrp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bKnrrp"><script>var topbKnrrp = {"Desktop":{"point":"0","unit":"px"}};var bottombKnrrp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7GFvGV","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
			<div class="section-wrapper" data-id="7GFvGV"><script>var top7GFvGV = {"Desktop":{"point":"0","unit":"px"}};var bottom7GFvGV = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-7GFvGV layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-o9lZgK"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-o9lZgK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="o9lZgK"><script>var topo9lZgK = {"Desktop":{"point":"0","unit":"px"}};var bottomo9lZgK = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-aZNCj5","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="aZNCj5"><script>var topaZNCj5 = {"Desktop":{"point":"0","unit":"px"}};var bottomaZNCj5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-aZNCj5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-7pLije","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7pLije"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7pLije"><script>var top7pLije = {"Desktop":{"point":"0","unit":"px"}};var bottom7pLije = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-lICvzB","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-lICvzB animated guten-element-hide desktop-fadeInUp">Best Service For You</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-e0HmOv","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"19","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"21","left":"21"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-e0HmOv animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-9yyP9k","textAlign":{"Desktop":"center"},"color":{"r":251,"g":250,"b":250,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"65","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0","Mobile":"0"},"lineHeight":{"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"65","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-18","right":"","left":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"top":"-30"}},"Mobile":{"unit":"%","dimension":{"top":"-85","right":"","bottom":"","left":"-2"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"default","Mobile":"default"},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Mobile":{"unit":"%","point":""}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-9yyP9k">S e r v i c e s</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-F92P6u","margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="F92P6u"><script>var topF92P6u = {"Desktop":{"point":"0","unit":"px"}};var bottomF92P6u = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-F92P6u layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-zpow0W","horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zpow0W animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zpow0W"><script>var topzpow0W = {"Desktop":{"point":"0","unit":"px"}};var bottomzpow0W = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-LfB6C3","imgSrc":{"media":{"imageId":223,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid-150x150.webp","orientation":"landscape"},"medium":{"height":267,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid-300x267.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid.webp","height":512,"width":576,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"height":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-LfB6C3"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/wand-magic-sparkles-solid.webp" height="512" width="576"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-eDt7lm","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element guten-icon-list guten-eDt7lm"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-MZQcYr","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-MZQcYr"><a id="guten-MZQcYr"><span class="list-text no-icon">Rescue Treatment</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-OHqBih","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OHqBih animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OHqBih"><script>var topOHqBih = {"Desktop":{"point":"0","unit":"px"}};var bottomOHqBih = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-huyC6r","imgSrc":{"media":{"imageId":224,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":188,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid-188x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid.webp","height":512,"width":320,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"35","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-huyC6r"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/bottle-droplet-solid.webp" height="512" width="320"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-k1nffZ","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13"}}}} -->
			<div class="guten-element guten-icon-list guten-k1nffZ"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-G11rm6","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-G11rm6"><a id="guten-G11rm6"><span class="list-text no-icon">Scalp Massage</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-P8by1D","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-P8by1D animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="P8by1D"><script>var topP8by1D = {"Desktop":{"point":"0","unit":"px"}};var bottomP8by1D = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-YpSkG5","imgSrc":{"media":{"imageId":225,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":225,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid-225x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid.webp","height":512,"width":384,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{},"Tablet":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-YpSkG5"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/droplet-solid.webp" height="512" width="384"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-qqZt8X","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13"}}}} -->
			<div class="guten-element guten-icon-list guten-qqZt8X"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-jVTAu9","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-jVTAu9"><a id="guten-jVTAu9"><span class="list-text no-icon">Body Scrub</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-y9oviT","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-y9oviT animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="y9oviT"><script>var topy9oviT = {"Desktop":{"point":"0","unit":"px"}};var bottomy9oviT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-dPBzc9","imgSrc":{"media":{"imageId":226,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid-300x300.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid.webp","height":512,"width":512,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-dPBzc9"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/plate-wheat-solid.webp" height="512" width="512"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-gAuerZ","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13"}}}} -->
			<div class="guten-element guten-icon-list guten-gAuerZ"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-3ILi2x","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-3ILi2x"><a id="guten-3ILi2x"><span class="list-text no-icon">Natural Mask</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-VoARKT","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-VoARKT animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VoARKT"><script>var topVoARKT = {"Desktop":{"point":"0","unit":"px"}};var bottomVoARKT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-DJ9ONM","imgSrc":{"media":{"imageId":227,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid-150x150.webp","orientation":"landscape"},"medium":{"height":240,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid-300x240.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid.webp","height":512,"width":640,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-DJ9ONM"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-sparkles-solid.webp" height="512" width="640"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-HyQpjD","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13"}}}} -->
			<div class="guten-element guten-icon-list guten-HyQpjD"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-SQt1zN","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-SQt1zN"><a id="guten-SQt1zN"><span class="list-text no-icon">Pranama Stone</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-zH2ogS","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zH2ogS animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zH2ogS"><script>var topzH2ogS = {"Desktop":{"point":"0","unit":"px"}};var bottomzH2ogS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Ho0zck","imgSrc":{"media":{"imageId":228,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid-150x150.webp","orientation":"landscape"},"medium":{"height":267,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid-300x267.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid.webp","height":512,"width":576,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Ho0zck"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-holding-droplet-solid.webp" height="512" width="576"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-CY624m","alignList":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.125"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"16"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"13"}}}} -->
			<div class="guten-element guten-icon-list guten-CY624m"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-KicTLu","hideIcon":true} -->
			<div class="guten-element guten-icon-list-item guten-KicTLu"><a id="guten-KicTLu"><span class="list-text no-icon">Swan Spa</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-bppDbG","margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}},"padding":{"Mobile":{}}} -->
			<div class="section-wrapper" data-id="bppDbG"><script>var topbppDbG = {"Desktop":{"point":"0","unit":"px"}};var bottombppDbG = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-bppDbG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-BXaVyd","background":{"type":"default","image":{"Desktop":{"id":338,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_NAQDACNUFE.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","left":"20","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-BXaVyd animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BXaVyd"><script>var topBXaVyd = {"Desktop":{"point":"0","unit":"px"}};var bottomBXaVyd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ux7C06","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"70","bottom":"5","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"224","bottom":"16","right":"32","left":"32"}}}} -->
			<div class="section-wrapper" data-id="ux7C06"><script>var topux7C06 = {"Desktop":{"point":"0","unit":"px"}};var bottomux7C06 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ux7C06 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-ZZzjdk","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"10","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"30","left":"30"}},"Tablet":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ZZzjdk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZZzjdk"><script>var topZZzjdk = {"Desktop":{"point":"0","unit":"px"}};var bottomZZzjdk = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-g7DhCU","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-g7DhCU">Sauna Relax</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-FGHVTa","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-FGHVTa"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae dictum ullamco.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-1T3R7F","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-1T3R7F"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-k0N7TQ","background":{"type":"default","image":{"Desktop":{"id":161,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_XVEZDYZASS.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-k0N7TQ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="k0N7TQ"><script>var topk0N7TQ = {"Desktop":{"point":"0","unit":"px"}};var bottomk0N7TQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Caq501","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"70","bottom":"5","right":"10","left":"10"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"224","bottom":"16","right":"32","left":"32"}}}} -->
			<div class="section-wrapper" data-id="Caq501"><script>var topCaq501 = {"Desktop":{"point":"0","unit":"px"}};var bottomCaq501 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Caq501 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-xFiP0a","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"10","right":"30","left":"30"}},"Mobile":{},"Tablet":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-xFiP0a"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="xFiP0a"><script>var topxFiP0a = {"Desktop":{"point":"0","unit":"px"}};var bottomxFiP0a = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ULNU8D","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-ULNU8D">Body Wraps</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-muXnPI","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-muXnPI"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae dictum ullamco.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-ALC4PV","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-ALC4PV"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-R94tOu","margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-R94tOu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="R94tOu"><script>var topR94tOu = {"Desktop":{"point":"0","unit":"px"}};var bottomR94tOu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Agwzzc","margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{},"Mobile":{}},"wrapColumn":{"Desktop":true,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="Agwzzc"><script>var topAgwzzc = {"Desktop":{"point":"0","unit":"px"}};var bottomAgwzzc = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Agwzzc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null,"Tablet":null},"elementId":"guten-qjm2JR","background":{"type":"default","image":{"Desktop":{"id":295,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_JF6DZWDDO3.webp"},"Mobile":{"id":295,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_JF6DZWDDO3.webp"}},"position":{"Desktop":"center center","Mobile":"top right"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"},"width":{"Desktop":{"point":"200","unit":"px"}}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"3","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-qjm2JR animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qjm2JR"><script>var topqjm2JR = {"Desktop":{"point":"0","unit":"px"}};var bottomqjm2JR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-HzB3ia","margin":{"Desktop":{"unit":"%","dimension":{"top":"5","bottom":"5","right":"40","left":"5"}},"Mobile":{"unit":"%","dimension":{"top":"10","right":"11","bottom":"10","left":"11"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"150"}}}} -->
			<div class="section-wrapper" data-id="HzB3ia"><script>var topHzB3ia = {"Desktop":{"point":"0","unit":"px"}};var bottomHzB3ia = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HzB3ia layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-691xUu","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{},"Mobile":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"7","right":"0","left":"7"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"30","bottom":"15","left":"30"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-691xUu"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="691xUu"><script>var top691xUu = {"Desktop":{"point":"0","unit":"px"}};var bottom691xUu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-faacQ7","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"positioningType":{"Desktop":"inline"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-faacQ7">Face Scrub</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-R6O1dH","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"20","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"20","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"10","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-R6O1dH"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullam.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-jm9KxL","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"buttonBorder":{"radius":{"Tablet":{}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-jm9KxL"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-VB4FsI","background":{"type":"default","image":{"Desktop":{"id":299,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_J1JY8GSUQF.webp"}},"position":{"Desktop":"bottom center","Mobile":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"","right":"0","bottom":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-VB4FsI animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="VB4FsI"><script>var topVB4FsI = {"Desktop":{"point":"0","unit":"px"}};var bottomVB4FsI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-obsQR5","margin":{"Desktop":{"unit":"%","dimension":{"top":"5","bottom":"5","right":"40","left":"5"}},"Mobile":{"unit":"%","dimension":{"top":"10","bottom":"10","right":"11","left":"11"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"150"}}}} -->
			<div class="section-wrapper" data-id="obsQR5"><script>var topobsQR5 = {"Desktop":{"point":"0","unit":"px"}};var bottomobsQR5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-obsQR5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-WtS4YQ","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"7","right":"0","left":"7"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-WtS4YQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WtS4YQ"><script>var topWtS4YQ = {"Desktop":{"point":"0","unit":"px"}};var bottomWtS4YQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-JyjruO","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"positioningType":{"Desktop":"inline"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-JyjruO">Skin Care</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-nPPsZ0","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"20","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"13"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{"unit":"px","dimension":{"bottom":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-nPPsZ0"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullam.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-6ydCLh","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-6ydCLh"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-NR4UaG","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"100"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="NR4UaG"><script>var topNR4UaG = {"Desktop":{"point":"0","unit":"px"}};var bottomNR4UaG = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-NR4UaG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-PnlQUd","background":{"type":"default","image":{"Desktop":{"id":162,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_ZTASYNHMPV.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-PnlQUd animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PnlQUd"><script>var topPnlQUd = {"Desktop":{"point":"0","unit":"px"}};var bottomPnlQUd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-W3c3FW","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"50","bottom":"5","right":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"221","right":"32","bottom":"16","left":"32"}}}} -->
			<div class="section-wrapper" data-id="W3c3FW"><script>var topW3c3FW = {"Desktop":{"point":"0","unit":"px"}};var bottomW3c3FW = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-W3c3FW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-sfFr6f","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"10","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-sfFr6f"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sfFr6f"><script>var topsfFr6f = {"Desktop":{"point":"0","unit":"px"}};var bottomsfFr6f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-CN9rHW","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-CN9rHW">Geothermal Sa</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-FQjw2d","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-FQjw2d"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae dictum ullamco.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-VCb1t3","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-VCb1t3"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-fblp3L","background":{"type":"default","image":{"Desktop":{"id":176,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_ETWN6UD9US.webp"}},"position":{"Desktop":"center left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-fblp3L animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="fblp3L"><script>var topfblp3L = {"Desktop":{"point":"0","unit":"px"}};var bottomfblp3L = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-y5mNcb","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"50","bottom":"5","right":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"224","bottom":"16","right":"32","left":"32"}}}} -->
			<div class="section-wrapper" data-id="y5mNcb"><script>var topy5mNcb = {"Desktop":{"point":"0","unit":"px"}};var bottomy5mNcb = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-y5mNcb layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-PCWdrQ","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"10","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"20","left":"20"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-PCWdrQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PCWdrQ"><script>var topPCWdrQ = {"Desktop":{"point":"0","unit":"px"}};var bottomPCWdrQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2BUsV7","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-2BUsV7">Natural Mask</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-OViWSo","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"20","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-OViWSo"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae dictum ullamco.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-OFEYDy","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-OFEYDy"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100},"elementId":"guten-nfeSLm","background":{"type":"default","image":{"Desktop":{"id":298,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_CUGFVFAI24.webp"}},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"10","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nfeSLm animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nfeSLm"><script>var topnfeSLm = {"Desktop":{"point":"0","unit":"px"}};var bottomnfeSLm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-tpz3y5","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"50","bottom":"5","right":"8","left":"8"}},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"top":"224","bottom":"16","right":"32","left":"32"}}}} -->
			<div class="section-wrapper" data-id="tpz3y5"><script>var toptpz3y5 = {"Desktop":{"point":"0","unit":"px"}};var bottomtpz3y5 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-tpz3y5 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-DlviuG","background":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"10","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"20","left":"20"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DlviuG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DlviuG"><script>var topDlviuG = {"Desktop":{"point":"0","unit":"px"}};var bottomDlviuG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-QJJiKg","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"500"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-QJJiKg">Floral Bath</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-G0gGK0","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Mobile":{"point":"20","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element gutenverse-text-editor guten-G0gGK0"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae dictum ullamco.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-NEAb6q","content":"View Detail","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":225,"g":214,"b":203,"a":1}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Mobile":{},"Tablet":{}},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-NEAb6q"><a class="guten-button guten-button-sm" href="#"><span>View Detail</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
