<?php
/**
 * Gutenverse Services Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Services Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-6jNzgz","background":{"type":"default","image":{"Desktop":{"id":165,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_VH22RVC5UT.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.7","bottomDivider":{"type":"waves","width":{"Desktop":"144"},"height":{"Desktop":"72"},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}}} -->
			<div class="section-wrapper" data-id="6jNzgz"><script>var top6jNzgz = {"Desktop":{"point":"0","unit":"px"}};var bottom6jNzgz = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6jNzgz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-m9ofKj"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-m9ofKj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="m9ofKj"><script>var topm9ofKj = {"Desktop":{"point":"0","unit":"px"}};var bottomm9ofKj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-syP3FM","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-syP3FM animated guten-element-hide desktop-fadeInDown">Services</h1>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
