<?php
/**
 * Gutenverse About Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 4', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-XmiHxq","margin":{"Desktop":{},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"50"}},"Tablet":{"unit":"px","dimension":{"bottom":"60"}}}} -->
			<div class="section-wrapper" data-id="XmiHxq"><script>var topXmiHxq = {"Desktop":{"point":"0","unit":"px"}};var bottomXmiHxq = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-XmiHxq layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-ZguWHt","margin":{"Mobile":{"unit":"px","dimension":{"right":"","top":"40"}},"Tablet":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ZguWHt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZguWHt"><script>var topZguWHt = {"Desktop":{"point":"0","unit":"px"}};var bottomZguWHt = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-8w9hTQ","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60"}}}} -->
			<div class="section-wrapper" data-id="8w9hTQ"><script>var top8w9hTQ = {"Desktop":{"point":"0","unit":"px"}};var bottom8w9hTQ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-8w9hTQ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Tablet":100,"Mobile":null},"elementId":"guten-lcmjvv","margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","left":"0","bottom":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lcmjvv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lcmjvv"><script>var toplcmjvv = {"Desktop":{"point":"0","unit":"px"}};var bottomlcmjvv = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wyaFnz","color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-wyaFnz animated guten-element-hide desktop-fadeInLeft">Professional Team</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-J4LbLS","color":{"r":251,"g":250,"b":250,"a":1},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"70","unit":"px"}},"spacing":{"Desktop":"0.2"}},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{}},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Mobile":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"point":"-21","unit":"px"},"Tablet":{"unit":"%","point":"-22"},"Mobile":{"unit":"%","point":"-14"}},"positioningBottom":{"Mobile":{"unit":"%","point":""}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-J4LbLS">Team</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-VgWd54","textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21","unit":"px"}}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"2","left":""}},"Mobile":{"unit":"%","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-VgWd54 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":null},"elementId":"guten-rPLDwm","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-rPLDwm"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rPLDwm"><script>var toprPLDwm = {"Desktop":{"point":"0","unit":"px"}};var bottomrPLDwm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-urpb3Y","content":"View All","alignButton":{"Desktop":"right","Tablet":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"60","left":"60"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}}},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":191,"g":164,"b":152,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"buttonBorderHover":{"radius":{"Mobile":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"border":{"radius":{"Mobile":{}}},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"padding":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"delay":"300","duration":"normal","type":{"Desktop":"fadeInRight"}},"color":{"r":191,"g":164,"b":152,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-urpb3Y"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>View All</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Mxn6P9","margin":{"Desktop":{"unit":"px","dimension":{"top":"60"}},"Tablet":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"","bottom":""}},"Mobile":{}}} -->
			<div class="section-wrapper" data-id="Mxn6P9"><script>var topMxn6P9 = {"Desktop":{"point":"0","unit":"px"}};var bottomMxn6P9 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Mxn6P9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-e3kRwE","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Tablet":{},"Mobile":{}},"animation":{"delay":"400","duration":"normal","type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-e3kRwE animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="e3kRwE"><script>var tope3kRwE = {"Desktop":{"point":"0","unit":"px"}};var bottome3kRwE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-AwteCQ","profileType":"overlay","overlayPosition":"bottom","src":{"id":253,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/woman-female-standing-fashion-clothing-outerwear-527822-pxhere.com.webp"},"name":"Dianne Russell","job":"FACE SPECIALIST","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"14.4","unit":"px"}},"spacing":{"Desktop":"0.125"}},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","left":"0","bottom":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","color":"","width":""}},"profileBorder":{"radius":{"Desktop":{}}},"imageBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hoverPadding":{"Desktop":{}},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-AwteCQ"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/woman-female-standing-fashion-clothing-outerwear-527822-pxhere.com.webp" alt="Dianne Russell"/><div class="profile-body bottom"><h3 class="profile-title ">Dianne Russell</h3><p class="profile-sub">FACE SPECIALIST</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-p1lCXw","iconSize":{"Desktop":{"point":"12","unit":"px"}},"shape":"circle","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"itemPadding":{"Desktop":{}},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icons guten-p1lCXw circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-gsGWaL","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-gsGWaL twitter"><a id="guten-gsGWaL"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-3EVmK0","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-3EVmK0 facebook"><a id="guten-3EVmK0"><i class="fab fa-facebook-f"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-NVT8NK","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-NVT8NK link"><a id="guten-NVT8NK"><i class="fab fa-linkedin-in"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-KHVRVb","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{}},"animation":{"delay":"500","duration":"normal","type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KHVRVb animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KHVRVb"><script>var topKHVRVb = {"Desktop":{"point":"0","unit":"px"}};var bottomKHVRVb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-HqCw9g","profileType":"overlay","overlayPosition":"bottom","src":{"id":254,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/person-people-girl-woman-hair-isolated-1354479-pxhere.com.webp"},"name":"Dianne Russell","job":"FACE SPECIALIST","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"14.4","unit":"px"}},"spacing":{"Desktop":"0.125"}},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"","color":""}},"profileBorder":{"radius":{"Desktop":{}}},"imageBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hoverPadding":{"Desktop":{}},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-HqCw9g"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/person-people-girl-woman-hair-isolated-1354479-pxhere.com.webp" alt="Dianne Russell"/><div class="profile-body bottom"><h3 class="profile-title ">Dianne Russell</h3><p class="profile-sub">FACE SPECIALIST</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-Ta20xb","iconSize":{"Desktop":{"point":"12","unit":"px"}},"shape":"circle","iconColor":{"r":0,"g":172,"b":238,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"itemPadding":{"Desktop":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-social-icons guten-Ta20xb circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-1NZ4QR","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-1NZ4QR twitter"><a id="guten-1NZ4QR"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-PHLk8X","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-PHLk8X facebook"><a id="guten-PHLk8X"><i class="fab fa-facebook-f"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-XFSwo7","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-XFSwo7 link"><a id="guten-XFSwo7"><i class="fab fa-linkedin-in"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-Ea6sxr","margin":{"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":{},"Mobile":{}},"animation":{"delay":"600","duration":"normal","type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Ea6sxr animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ea6sxr"><script>var topEa6sxr = {"Desktop":{"point":"0","unit":"px"}};var bottomEa6sxr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-DYhVa6","profileType":"overlay","overlayPosition":"bottom","src":{"id":255,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/people-girl-woman-hair-isolated-female-1260525-pxhere.com.webp"},"name":"Dianne Russell","job":"FACE SPECIALIST","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"14.4","unit":"px"}},"spacing":{"Desktop":"0.125"}},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":{}},"all":{"type":"none","width":"","color":""}},"profileBorder":{"radius":{"Desktop":{}}},"imageBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hoverPadding":{"Desktop":{}},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-DYhVa6"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/people-girl-woman-hair-isolated-female-1260525-pxhere.com.webp" alt="Dianne Russell"/><div class="profile-body bottom"><h3 class="profile-title ">Dianne Russell</h3><p class="profile-sub">FACE SPECIALIST</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-6O3W3c","iconSize":{"Desktop":{"point":"12","unit":"px"}},"shape":"circle","iconColor":{"r":0,"g":172,"b":238,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"itemPadding":{"Desktop":{}}} -->
			<div class="guten-element guten-social-icons guten-6O3W3c circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-VrluNE","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-VrluNE twitter"><a id="guten-VrluNE"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-9fN7yt","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-9fN7yt facebook"><a id="guten-9fN7yt"><i class="fab fa-facebook-f"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-s1Bnu5","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-s1Bnu5 link"><a id="guten-s1Bnu5"><i class="fab fa-linkedin-in"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-7Pvcy0","margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"delay":"700","duration":"normal","type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7Pvcy0 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7Pvcy0"><script>var top7Pvcy0 = {"Desktop":{"point":"0","unit":"px"}};var bottom7Pvcy0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-ZzKgk8","profileType":"overlay","overlayPosition":"bottom","src":{"id":256,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/girl-woman-female-standing-fashion-clothing-527819-pxhere.com.webp"},"name":"Dianne Russell","job":"FACE SPECIALIST","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"600"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"14.4","unit":"px"}},"spacing":{"Desktop":"0.125"}},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":{}},"all":{"type":"none","width":"","color":""}},"profileBorder":{"radius":{"Desktop":{}}},"imageBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":191,"g":164,"b":152,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hoverPadding":{"Desktop":{}},"hoverContentBorder":{"radius":{"Desktop":{}}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-ZzKgk8"><div class="profile-box"><div class="profile-card card-overlay undefined"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/girl-woman-female-standing-fashion-clothing-527819-pxhere.com.webp" alt="Dianne Russell"/><div class="profile-body bottom"><h3 class="profile-title ">Dianne Russell</h3><p class="profile-sub">FACE SPECIALIST</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LZ7Nma","iconSize":{"Desktop":{"point":"12","unit":"px"}},"shape":"circle","iconColor":{"r":0,"g":172,"b":238,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"itemPadding":{"Desktop":{}}} -->
			<div class="guten-element guten-social-icons guten-LZ7Nma circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-7sUjc3","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-7sUjc3 twitter"><a id="guten-7sUjc3"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-pEpgld","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-pEpgld facebook"><a id="guten-pEpgld"><i class="fab fa-facebook-f"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->
			
			<!-- wp:gutenverse/social-icon {"elementId":"guten-z0WfFz","iconColor":{"r":191,"g":164,"b":152,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":191,"g":164,"b":152,"a":1}} -->
			<div class="guten-element guten-social-icon guten-z0WfFz link"><a id="guten-z0WfFz"><i class="fab fa-linkedin-in"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
