<?php
/**
 * Gutenverse About Hero content.
 */
return array(
	'title'      => __( 'Gutenverse About Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-UwbmVX","background":{"type":"default","image":{"Desktop":{"id":140,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.7","bottomDivider":{"type":"waves","width":{"Desktop":"144","Mobile":"132","Tablet":"187"},"height":{"Desktop":"117","Mobile":"90","Tablet":"90"},"flip":false,"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"100"}}}} -->
			<div class="section-wrapper" data-id="UwbmVX"><script>var topUwbmVX = {"Desktop":{"point":"0","unit":"px"}};var bottomUwbmVX = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-UwbmVX layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-u06Eo5"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-u06Eo5"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="u06Eo5"><script>var topu06Eo5 = {"Desktop":{"point":"0","unit":"px"}};var bottomu06Eo5 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"48","unit":"px"},"Tablet":{"point":"80","unit":"px"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"400","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"decoration":"default","style":"italic"},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide desktop-fadeInDown">Our Spa</h1>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
