<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":143,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/nature-plant-leaf-flower-petal-glass-612874-pxhere.com.webp"}},"position":{"Desktop":"bottom center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","border":{"radius":{"Tablet":[],"Desktop":[]}},"bottomDivider":{"type":"waves","width":{"Desktop":"144","Tablet":"174"},"flip":false,"height":{"Desktop":"90","Tablet":"100"},"colorMode":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"150","bottom":"200"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="4qr4Df"><script>var top4qr4Df = {"Desktop":{"point":"0","unit":"px"}};var bottom4qr4Df = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-3vgI6y"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3vgI6y"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vgI6y"><script>var top3vgI6y = {"Desktop":{"point":"0","unit":"px"}};var bottom3vgI6y = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","type":1,"textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"48","unit":"px"},"Tablet":{"point":"80","unit":"px"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"400","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"decoration":"default","style":"italic"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"slideInDown","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"normal","delay":""}} -->
			<h1 class="wp-block-gutenverse-heading guten-element guten-q3mXI6 animated guten-element-hide desktop-slideInDown tablet-fadeInDown mobile-fadeInDown">Beauty Spa, Relaxing &amp; Wellness Center</h1>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","alignment":{"Desktop":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"15","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"28.8","unit":"px"},"Tablet":{"point":"27","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"0","bottom":"0","left":"120"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40","left":"40"}}},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInUp","Mobile":"slideInUp"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-kxbE7L animated guten-element-hide desktop-fadeInDown tablet-fadeInUp mobile-slideInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Quisque consectetur convallis exquis tincidunt ligula placeratet. Nam quis leo sed tortor blandit commodo. Quisque ultrices justo non convallis accumsan ante magna ornare sapien quis venenatis diam libero necorci.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-DPwJel","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="DPwJel"><script>var topDPwJel = {"Desktop":{"point":"0","unit":"px"}};var bottomDPwJel = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-DPwJel layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-HIN6fa","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HIN6fa"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HIN6fa"><script>var topHIN6fa = {"Desktop":{"point":"0","unit":"px"}};var bottomHIN6fa = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-i0nEgV","content":"Get Started","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":191,"g":164,"b":152,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","color":{"r":191,"g":164,"b":152,"a":1},"width":"1"}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}}} -->
			<div class="guten-element guten-button-wrapper guten-i0nEgV"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Get Started</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-jhBZEQ"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jhBZEQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jhBZEQ"><script>var topjhBZEQ = {"Desktop":{"point":"0","unit":"px"}};var bottomjhBZEQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-8s3F5w","content":"Book An Appoinement","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInRight","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"200"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":225,"g":214,"b":203,"a":1},"className":"elementor-animation-wobble-horizontal"} -->
			<div class="guten-element guten-button-wrapper guten-8s3F5w elementor-animation-wobble-horizontal"><a class="guten-button animated guten-element-hide desktop-fadeInRight tablet-fadeInRight mobile-fadeInRight guten-button-sm" href="#"><span>Book An Appoinement</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
