<?php
/**
 * Gutenverse About Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-TlTjon","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="TlTjon"><script>var topTlTjon = {"Desktop":{"point":"0","unit":"px"}};var bottomTlTjon = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-TlTjon layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":null},"elementId":"guten-vV4rJH","margin":{"Tablet":{},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vV4rJH"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vV4rJH"><script>var topvV4rJH = {"Desktop":{"point":"0","unit":"px"}};var bottomvV4rJH = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-aM1B5R","margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"5","left":"5","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"0","right":"10","left":"10"}}}} -->
			<div class="section-wrapper" data-id="aM1B5R"><script>var topaM1B5R = {"Desktop":{"point":"0","unit":"px"}};var bottomaM1B5R = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-aM1B5R layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-DYjRwA","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"10","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-DYjRwA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="DYjRwA"><script>var topDYjRwA = {"Desktop":{"point":"0","unit":"px"}};var bottomDYjRwA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-zQgZ3t","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="zQgZ3t"><script>var topzQgZ3t = {"Desktop":{"point":"0","unit":"px"}};var bottomzQgZ3t = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-zQgZ3t layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-9aGyS1","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9aGyS1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9aGyS1"><script>var top9aGyS1 = {"Desktop":{"point":"0","unit":"px"}};var bottom9aGyS1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Pp6VLb","imgSrc":{"media":{"imageId":53,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-300x300.webp","orientation":"landscape"},"large":{"height":1024,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1-1024x1024.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp","height":1920,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"102","unit":"px"},"Tablet":{"point":"146","unit":"px"},"Mobile":{"point":"58","unit":"px"}},"height":{"Desktop":{"point":"102","unit":"px"},"Tablet":{"point":"145","unit":"px"},"Mobile":{"point":"57","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Pp6VLb animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Logo-1.webp" height="1920" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-nuAQtp","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"42","unit":"px"},"Tablet":{"point":"46","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"46","unit":"px"},"Mobile":{"point":"42","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-nuAQtp animated guten-element-hide desktop-fadeInLeft">An Incredible Spa Experience</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-rbVW8W","dropcapMargin":{},"dropcapPadding":{},"alignment":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"%","dimension":{"right":"5","left":"5"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-rbVW8W animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisl. </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/image {"elementId":"guten-uX2DHt","imgSrc":{"media":{"imageId":88,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-150x150.webp","orientation":"landscape"},"medium":{"height":71,"width":300,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-300x71.webp","orientation":"landscape"},"large":{"height":244,"width":1024,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan-1024x244.webp","orientation":"landscape"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp","height":457,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"205","unit":"px"},"Tablet":{"point":"218","unit":"px"},"Mobile":{"point":"145","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"43","unit":"px"},"Mobile":{"point":"29","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"zIndex":{"Desktop":"10"}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-uX2DHt animated guten-element-hide desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/Tandatangan.webp" height="457" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-REHQzp","type":5,"textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-REHQzp animated guten-element-hide desktop-fadeInLeft">WaterLava Owner</h5>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50},"elementId":"guten-chAEvr","order":{"Tablet":2}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-chAEvr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="chAEvr"><script>var topchAEvr = {"Desktop":{"point":"0","unit":"px"}};var bottomchAEvr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Tm5j7e","imgSrc":{"media":{"imageId":262,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":184,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-184x300.webp","orientation":"portrait"},"large":{"height":1024,"width":627,"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com-627x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com.webp","height":2450,"width":1500,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"410","unit":"px"},"Mobile":{"point":"251","unit":"px"}},"height":{"Mobile":{"point":"361","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"200"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"-10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Tm5j7e animated guten-element-hide desktop-fadeIn"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( WATERLAVA_URI ) . 'assets/img/hand-person-woman-white-young-finger-814735-pxhere.com.webp" height="2450" width="1500"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":null},"elementId":"guten-OhTrmI","order":{"Tablet":1},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"5","left":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"20"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OhTrmI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OhTrmI"><script>var topOhTrmI = {"Desktop":{"point":"0","unit":"px"}};var bottomOhTrmI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-JzHGMF","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"weight":"600"},"margin":{"Mobile":{}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-JzHGMF animated guten-element-hide desktop-fadeInRight">1998</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-Qhqu3X","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":44,"b":57,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-Qhqu3X animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna.&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-GbdA2Z","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"weight":"600"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}},"padding":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-GbdA2Z animated guten-element-hide desktop-fadeInRight">Awards</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-cBA1Ok","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="cBA1Ok"><script>var topcBA1Ok = {"Desktop":{"point":"0","unit":"px"}};var bottomcBA1Ok = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-cBA1Ok layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-i2siCg","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-i2siCg animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="i2siCg"><script>var topi2siCg = {"Desktop":{"point":"0","unit":"px"}};var bottomi2siCg = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-4988X8","iconColor":{"r":58,"g":44,"b":57,"a":1},"iconColorHover":{"r":58,"g":44,"b":57,"a":1},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textIndent":{"Desktop":"5"},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}}}} -->
			<div class="guten-element guten-icon-list guten-4988X8"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-8cgn72"} -->
			<div class="guten-element guten-icon-list-item guten-8cgn72"><a id="guten-8cgn72"><i class="fas fa-medal"></i><span class="list-text ">The Edge Bali</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-IHArFy"} -->
			<div class="guten-element guten-icon-list-item guten-IHArFy"><a id="guten-IHArFy"><i class="fas fa-medal"></i><span class="list-text ">The Ritz Calton</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vtVNmZ"} -->
			<div class="guten-element guten-icon-list-item guten-vtVNmZ"><a id="guten-vtVNmZ"><i class="fas fa-medal"></i><span class="list-text ">Laggona Cliff</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-KhxKQN","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KhxKQN animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KhxKQN"><script>var topKhxKQN = {"Desktop":{"point":"0","unit":"px"}};var bottomKhxKQN = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-BydsM9","iconColor":{"r":58,"g":44,"b":57,"a":1},"iconColorHover":{"r":58,"g":44,"b":57,"a":1},"textColor":{"r":58,"g":44,"b":57,"a":1},"textColorHover":{"r":58,"g":44,"b":57,"a":1},"textIndent":{"Desktop":"5"},"textTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"25.2","unit":"px"},"Tablet":{"point":"23.4","unit":"px"},"Mobile":{"point":"21.6","unit":"px"}},"weight":"400"}} -->
			<div class="guten-element guten-icon-list guten-BydsM9"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-gAgIm0"} -->
			<div class="guten-element guten-icon-list-item guten-gAgIm0"><a id="guten-gAgIm0"><i class="fas fa-medal"></i><span class="list-text ">Global Spa Awards</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ZZX0hy"} -->
			<div class="guten-element guten-icon-list-item guten-ZZX0hy"><a id="guten-ZZX0hy"><i class="fas fa-medal"></i><span class="list-text ">Best Resort Spa</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-y3zHQs"} -->
			<div class="guten-element guten-icon-list-item guten-y3zHQs"><a id="guten-y3zHQs"><i class="fas fa-medal"></i><span class="list-text ">Dive\'s Awards</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-rokpoV","textAlign":{"Desktop":"center"},"color":{"r":80,"g":65,"b":74,"a":1},"typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"36","unit":"px"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-rokpoV animated guten-element-hide desktop-fadeInRight">Our Specialist</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/progress-bar {"elementId":"guten-UREabw","title":"Face Tratements","percentage":"90","barColor":{"r":237,"g":237,"b":237,"a":1},"trackColor":{"r":191,"g":164,"b":152,"a":1},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{},"Tablet":{}},"trackRadius":{"Desktop":{},"Tablet":{}},"barPadding":{"Desktop":{},"Tablet":{}},"barMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"r":80,"g":65,"b":74,"a":1},"titleTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}}},"percentColor":{"r":80,"g":65,"b":74,"a":1},"percentTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
			<div class="guten-element guten-progress-bar guten-UREabw animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Face Tratements</span></div><div class="skill-bar"><div class="skill-track" data-width="90" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar -->
			
			<!-- wp:gutenverse/progress-bar {"elementId":"guten-yGblgz","title":"Scalp Massage","percentage":"97","barColor":{"r":237,"g":237,"b":237,"a":1},"trackColor":{"r":191,"g":164,"b":152,"a":1},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":80,"g":65,"b":74,"a":1},"titleTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}}},"percentColor":{"r":80,"g":65,"b":74,"a":1},"percentTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
			<div class="guten-element guten-progress-bar guten-yGblgz animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Scalp Massage</span></div><div class="skill-bar"><div class="skill-track" data-width="97" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar -->
			
			<!-- wp:gutenverse/progress-bar {"elementId":"guten-Y7DS2X","title":"Natural Mask","percentage":"93","barColor":{"r":237,"g":237,"b":237,"a":1},"trackColor":{"r":191,"g":164,"b":152,"a":1},"trackHeight":{"Desktop":"3"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":80,"g":65,"b":74,"a":1},"titleTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}}},"percentColor":{"r":80,"g":65,"b":74,"a":1},"percentTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"}},"lineHeight":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"25.5","unit":"px"}},"weight":"600"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"0","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
			<div class="guten-element guten-progress-bar guten-Y7DS2X animated guten-element-hide desktop-fadeInRight"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Natural Mask</span></div><div class="skill-bar"><div class="skill-track" data-width="93" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
