<?php
/**
 * Gutenverse Home Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 4', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-hUZiaL","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"0","left":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="hUZiaL"><script>var tophUZiaL = {"Desktop":{"point":"0","unit":"px"}};var bottomhUZiaL = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-hUZiaL layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"elementId":"guten-RdWIvY","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RdWIvY animated guten-element-hide desktop-fadeInRight tablet-fadeInRight mobile-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RdWIvY"><script>var topRdWIvY = {"Desktop":{"point":"0","unit":"px"}};var bottomRdWIvY = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-OYmIYu","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":166,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/woman-skin-spa-beauty-nose-neck-1604350-pxhere.com.webp"},"name":"Wellness","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus","showSocial":false,"nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"45","unit":"px"}}},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"}}},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow","delay":"1"},"imgHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-OYmIYu animated guten-element-hide slow desktop-fadeInRight"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/woman-skin-spa-beauty-nose-neck-1604350-pxhere.com.webp" alt="Wellness"/><div class="profile-body center"><h3 class="profile-title ">Wellness</h3><p class="profile-sub">Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus</p></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"elementId":"guten-UAUXFE","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-UAUXFE animated guten-element-hide desktop-fadeInLeft tablet-fadeInLeft mobile-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UAUXFE"><script>var topUAUXFE = {"Desktop":{"point":"0","unit":"px"}};var bottomUAUXFE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-wNv2Pe","profileType":"overlay","overlayType":"default","overlayPosition":"center","src":{"id":165,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_VH22RVC5UT.webp"},"name":"Treatment","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"r":255,"g":255,"b":255,"a":1},"nameColorHover":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"45","unit":"px"}}},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobColorHover":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"25.2","unit":"px"}}},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"slideInLeft"},"duration":"slow","delay":"2"},"imgHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-wNv2Pe animated guten-element-hide slow desktop-slideInLeft"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_VH22RVC5UT.webp" alt="Treatment"/><div class="profile-body center"><h3 class="profile-title ">Treatment</h3><p class="profile-sub">Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.</p></div></div></div></div>
			<!-- /wp:gutenverse/team --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
