<?php
/**
 * Gutenverse Single Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Single Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-4qr4Df","verticalAlign":"center","background":{"type":"default","image":{"Desktop":{"id":161,"image":"' . esc_url( WATERLAVA_URI ) . 'assets/img/StockSnap_XVEZDYZASS.webp"}},"position":{"Desktop":"center center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","topDivider":{"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"bottomDivider":{"type":"waves","width":{"Desktop":"144"},"flip":false,"height":{"Desktop":"99","Mobile":"71"},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"150","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"150","right":"10","left":"10"}}},"animation":{"type":{"Desktop":"none"}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="4qr4Df"><script>var top4qr4Df = {"Desktop":{"point":"0","unit":"px"}};var bottom4qr4Df = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"><svg fill="none" height="143" class="guten-shape-fill" viewBox="0 0 1200 143" preserveAspectRatio="none" width="1200" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m1200 20.0467h-33c-34 0-100 0-167 24.0561s-133 72.1682-200 90.2102-133 6.014-200-18.042c-67-24.0561-133-60.1402-200-78.1822-67-18.0421-133-18.0421-200 0-67 18.042-133 54.1261-167 72.1682l-33 18.042v-128.299h1200z" fill="#000" fill-rule="evenodd"></path></svg></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":1400,"Tablet":null},"elementId":"guten-3vgI6y","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"flex-start"},"margin":{"Tablet":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3vgI6y animated guten-element-hide desktop-fadeInDown"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vgI6y"><script>var top3vgI6y = {"Desktop":{"point":"0","unit":"px"}};var bottom3vgI6y = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/post-title {"elementId":"guten-BoThEm","alignment":{"Desktop":"center","Tablet":"center"},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"lineHeight":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"weight":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-post-title guten-BoThEm"></div>
			<!-- /wp:gutenverse/post-title -->
			
			<!-- wp:gutenverse/icon {"elementId":"guten-JPXaCb","icon":"far fa-user","iconAlign":{"Tablet":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconShape":"custom","iconBorderRadius":{},"margin":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Tablet":{"unit":"%","dimension":{"left":"30","right":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-JPXaCb guten-icon"><span class="guten-icon-wrapper custom stacked"><i class="far fa-user"></i></span></div>
			<!-- /wp:gutenverse/icon -->
			
			<!-- wp:gutenverse/post-author {"elementId":"guten-DTfkFX","typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"18","unit":"px"}}},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-post-author guten-DTfkFX"></div>
			<!-- /wp:gutenverse/post-author -->
			
			<!-- wp:gutenverse/icon {"elementId":"guten-DX3Gvh","icon":"far fa-calendar","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-DX3Gvh guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="far fa-calendar"></i></span></div>
			<!-- /wp:gutenverse/icon -->
			
			<!-- wp:gutenverse/post-date {"elementId":"guten-x55IKW","typography":{"font":{"label":"EB Garamond","value":"EB Garamond","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"point":"18","unit":"px"}}},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"%","dimension":{"right":"29","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-post-date guten-x55IKW"></div>
			<!-- /wp:gutenverse/post-date --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
